# Generated by Django 6.0.5 on 2026-05-29 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionario', '0034_add_painelrecebimento_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('codigo', models.SlugField(max_length=40, unique=True, verbose_name='Código')),
                ('icone', models.CharField(default='file-text', help_text='Nome do ícone Lucide (ex: file-text, clipboard, file-check)', max_length=40, verbose_name='Ícone Lucide')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(help_text='Formatos aceitos: PDF, DOCX, DOC', upload_to='documentos/', verbose_name='Arquivo')),
                ('plano_minimo', models.CharField(choices=[('start', 'START'), ('plus', 'PLUS'), ('elite', 'ELITE')], default='start', max_length=10, verbose_name='Plano mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.categoriadocumento', verbose_name='Categoria')),
                ('especialidades', models.ManyToManyField(blank=True, help_text='Deixe vazio para disponibilizar para TODAS as especialidades', to='questionario.especialidade', verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['categoria__ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='DownloadDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baixado_em', models.DateTimeField(auto_now_add=True, verbose_name='Baixado em')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documentos.documento', verbose_name='Documento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads_doc', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Download de Documento',
                'verbose_name_plural': 'Downloads de Documentos',
                'ordering': ['-baixado_em'],
            },
        ),
    ]
