# Generated by Django 6.0.5 on 2026-05-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='Formatos aceitos: PDF, DOCX, DOC', max_length=500, upload_to='documentos/', verbose_name='Arquivo'),
        ),
    ]
