# Generated by Django 6.0.4 on 2026-04-27 00:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Nome do responsável')),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pont_auditiva', models.IntegerField(blank=True, null=True)),
                ('pont_visual', models.IntegerField(blank=True, null=True)),
                ('pont_tato', models.IntegerField(blank=True, null=True)),
                ('pont_movimento', models.IntegerField(blank=True, null=True)),
                ('pont_posicao', models.IntegerField(blank=True, null=True)),
                ('pont_oral', models.IntegerField(blank=True, null=True)),
                ('pont_conduta', models.IntegerField(blank=True, null=True)),
                ('pont_socioemocional', models.IntegerField(blank=True, null=True)),
                ('pont_atencao', models.IntegerField(blank=True, null=True)),
                ('pont_ex', models.IntegerField(blank=True, null=True)),
                ('pont_ev', models.IntegerField(blank=True, null=True)),
                ('pont_sn', models.IntegerField(blank=True, null=True)),
                ('pont_ob', models.IntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(blank=True, max_length=20, verbose_name='CRM')),
                ('especialidade', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Médico',
                'verbose_name_plural': 'Perfis dos Médicos',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(verbose_name='Número do item')),
                ('valor', models.IntegerField(verbose_name='Pontuação (0-5)')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacao')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
