# Generated by Django 6.0.4 on 2026-04-29 13:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_avaliacao_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pont_total', models.FloatField(blank=True, null=True)),
                ('pont_comunicacao', models.FloatField(blank=True, null=True)),
                ('pont_locomocao', models.FloatField(blank=True, null=True)),
                ('pont_ocupacao', models.FloatField(blank=True, null=True)),
                ('pont_socializacao', models.FloatField(blank=True, null=True)),
                ('pont_autogoverno', models.FloatField(blank=True, null=True)),
                ('pont_age', models.FloatField(blank=True, null=True)),
                ('pont_ac', models.FloatField(blank=True, null=True)),
                ('pont_av', models.FloatField(blank=True, null=True)),
                ('idade_social_meses', models.IntegerField(blank=True, null=True, verbose_name='Idade Social (meses)')),
                ('quociente_social', models.FloatField(blank=True, null=True, verbose_name='Quociente Social (QS)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_vineland', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Avaliação Vineland',
                'verbose_name_plural': 'Avaliações Vineland',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(verbose_name='Número do item')),
                ('resposta', models.CharField(choices=[('sim_sempre', 'Sim, sempre'), ('sim_as_vezes', 'Sim, às vezes'), ('nao_nunca', 'Não, nunca'), ('nao_oportunidade', 'Não teve oportunidade'), ('nao_sei', 'Não sei')], max_length=20)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaovineland')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
