# Generated by Django 6.0.4 on 2026-05-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0005_rename_crm_to_registro_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações clínicas'),
        ),
        migrations.AddField(
            model_name='avaliacaovineland',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='avaliacaovineland',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações clínicas'),
        ),
    ]
