# Generated by Django 6.0.4 on 2026-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0007_new_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaobebe',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='avaliacaobebe',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='avaliacaoescolar',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='avaliacaoescolar',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
