# Generated by Django 6.0.4 on 2026-05-05 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0008_token_email_escolar_bebe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkConvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tipo', models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_convite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link de Convite',
                'verbose_name_plural': 'Links de Convite',
                'ordering': ['-criado_em'],
            },
        ),
    ]
