# Generated by Django 6.0.4 on 2026-05-11 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0009_link_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI')], max_length=20),
        ),
        migrations.CreateModel(
            name='AvaliacaoSPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('faixa', models.CharField(choices=[('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)')], max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_soc', models.IntegerField(blank=True, null=True)),
                ('pont_vis', models.IntegerField(blank=True, null=True)),
                ('pont_hea', models.IntegerField(blank=True, null=True)),
                ('pont_tou', models.IntegerField(blank=True, null=True)),
                ('pont_sme', models.IntegerField(blank=True, null=True)),
                ('pont_bod', models.IntegerField(blank=True, null=True)),
                ('pont_bal', models.IntegerField(blank=True, null=True)),
                ('pont_pla', models.IntegerField(blank=True, null=True)),
                ('pont_tot', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações clínicas')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_spm', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'SPM',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaSPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaospm')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
