# Generated by Django 4.2.11 on 2026-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0010_spm_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Perfil Sensorial Bebê/Criança Pequena'), ('spm', 'SPM — Sensory Processing Measure'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI')], max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Módulo de Avaliação',
                'verbose_name_plural': 'Módulos de Avaliação',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='modulos_liberados',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='questionario.moduloavaliacao', verbose_name='Módulos liberados'),
        ),
    ]
