# Generated by Django 4.2.11 on 2026-05-13 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0012_popular_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoVineland3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_com', models.IntegerField(blank=True, null=True, verbose_name='COM — Comunicação')),
                ('pont_avd', models.IntegerField(blank=True, null=True, verbose_name='AVD — Atividade de Vida Diária')),
                ('pont_soc', models.IntegerField(blank=True, null=True, verbose_name='SOC — Habilidades Sociais')),
                ('pont_hmot', models.IntegerField(blank=True, null=True, verbose_name='HMOT — Atividade Física')),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Composto Adaptativo')),
                ('pont_pc_a', models.IntegerField(blank=True, null=True, verbose_name='PC — Seção A')),
                ('pont_pc_b', models.IntegerField(blank=True, null=True, verbose_name='PC — Seção B')),
                ('pont_pc_c', models.IntegerField(blank=True, null=True, verbose_name='PC — Seção C')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações clínicas')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_vineland3', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Vineland-3',
                'ordering': ['-data'],
            },
        ),
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3')], max_length=20),
        ),
        migrations.CreateModel(
            name='RespostaVineland3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaovineland3')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
