# Generated by Django 4.2.11 on 2026-05-13 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0014_vineland3_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_soc', models.IntegerField(blank=True, null=True, verbose_name='Socialização — SIM')),
                ('pont_cog', models.IntegerField(blank=True, null=True, verbose_name='Cognição — SIM')),
                ('pont_lin', models.IntegerField(blank=True, null=True, verbose_name='Linguagem — SIM')),
                ('pont_ac', models.IntegerField(blank=True, null=True, verbose_name='Auto-Cuidados — SIM')),
                ('pont_mot', models.IntegerField(blank=True, null=True, verbose_name='Motor — SIM')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações clínicas')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_portage', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Guia Portage',
                'ordering': ['-data'],
            },
        ),
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moduloavaliacao',
            name='codigo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Perfil Sensorial Bebê/Criança Pequena'), ('spm', 'SPM — Sensory Processing Measure'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage')], max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='RespostaPortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=20)),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoportage')),
            ],
            options={
                'ordering': ['dominio', 'numero_item'],
                'unique_together': {('avaliacao', 'dominio', 'numero_item')},
            },
        ),
    ]
