# Generated by Django 4.2.11 on 2026-05-15 13:24

from django.db import migrations, models

NOVOS_MODULOS = [
    ("sdq",                    "SDQ — Capacidades e Dificuldades",         "SDQ — Strengths and Difficulties Questionnaire"),
    ("snap_iv",                "SNAP-IV — Avaliação de TDAH/TOD",          "Swanson, Nolan and Pelham Rating Scale"),
    ("mchat",                  "M-CHAT-R — Rastreio de Autismo",           "Modified Checklist for Autism in Toddlers, Revised"),
    ("cars",                   "CARS-2 — Escala de Autismo em Crianças",   "Childhood Autism Rating Scale"),
    ("linguagem",              "Avaliação de Linguagem",                   "Checklist clínico de avaliação de linguagem — Fonoaudiologia"),
    ("alimentacao_seletiva",   "Triagem de Alimentação Seletiva",          "Seletividade alimentar e disfagia / processamento oral-motor"),
    ("desenvolvimento",        "Marcos de Desenvolvimento Infantil",       "Checklist de marcos do desenvolvimento infantil"),
    ("sono_infantil",          "Avaliação de Sono Infantil",               "Triagem de distúrbios do sono — BEARS/CSHQ adaptado"),
    ("habilidades_adaptativas","Habilidades Adaptativas (ABA)",            "Checklist de habilidades adaptativas para ABA"),
    ("comportamento_funcional","Comportamento Funcional (ABA)",            "Rastreio de comportamento funcional"),
    ("rastreio_cognitivo",     "Rastreio Cognitivo",                       "Rastreio neuropsicológico de atenção, memória e funções executivas"),
    ("psicopedagogica",        "Avaliação Psicopedagógica",                "Rastreio de dificuldades de aprendizagem"),
]


def popular_novos_modulos(apps, schema_editor):
    ModuloAvaliacao = apps.get_model("questionario", "ModuloAvaliacao")
    for codigo, nome, descricao in NOVOS_MODULOS:
        ModuloAvaliacao.objects.get_or_create(
            codigo=codigo,
            defaults={"nome": nome, "descricao": descricao},
        )


def remover_novos_modulos(apps, schema_editor):
    ModuloAvaliacao = apps.get_model("questionario", "ModuloAvaliacao")
    ModuloAvaliacao.objects.filter(codigo__in=[m[0] for m in NOVOS_MODULOS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0018_novos_questionarios_multiprofissionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmedico',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('terapeuta_ocupacional', 'Terapia Ocupacional'), ('psicologo', 'Psicologia'), ('fonoaudiologo', 'Fonoaudiologia'), ('neuropsicoplogo', 'Neuropsicologia'), ('psicopedagogo', 'Psicopedagogia'), ('pediatra', 'Pediatria'), ('neuropediatra', 'Neuropediatria'), ('analista_aba', 'ABA / Análise do Comportamento')], max_length=30, verbose_name='Especialidade'),
        ),
        migrations.RunPython(popular_novos_modulos, remover_novos_modulos),
    ]
