# Generated by Django 4.2.11 on 2026-05-15 13:33

from django.db import migrations, models

ESPECIALIDADES = [
    ("analista_aba",          "ABA / Análise do Comportamento"),
    ("fonoaudiologo",         "Fonoaudiologia"),
    ("neuropediatra",         "Neuropediatria"),
    ("neuropsicoplogo",       "Neuropsicologia"),
    ("pediatra",              "Pediatria"),
    ("psicologo",             "Psicologia"),
    ("psicopedagogo",         "Psicopedagogia"),
    ("terapeuta_ocupacional", "Terapia Ocupacional"),
]


def popular_especialidades(apps, schema_editor):
    Especialidade = apps.get_model("questionario", "Especialidade")
    for codigo, nome in ESPECIALIDADES:
        Especialidade.objects.get_or_create(codigo=codigo, defaults={"nome": nome})


def remover_especialidades(apps, schema_editor):
    Especialidade = apps.get_model("questionario", "Especialidade")
    Especialidade.objects.filter(codigo__in=[e[0] for e in ESPECIALIDADES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0019_popular_novos_modulos_e_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('terapeuta_ocupacional', 'Terapia Ocupacional'), ('psicologo', 'Psicologia'), ('fonoaudiologo', 'Fonoaudiologia'), ('neuropsicoplogo', 'Neuropsicologia'), ('psicopedagogo', 'Psicopedagogia'), ('pediatra', 'Pediatria'), ('neuropediatra', 'Neuropediatria'), ('analista_aba', 'ABA / Análise do Comportamento')], max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(popular_especialidades, remover_especialidades),
        migrations.RemoveField(
            model_name='perfilmedico',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='questionario.especialidade', verbose_name='Especialidades'),
        ),
    ]
