# Generated by Django 6.0.5 on 2026-05-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0020_especialidade_model_e_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Chave de sessão ativa'),
        ),
    ]
