# Generated by Django 6.0.5 on 2026-05-18 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0021_perfilmedico_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('dispositivo', models.CharField(blank=True, max_length=120, verbose_name='Dispositivo')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent completo')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Login bem-sucedido')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Login',
                'verbose_name_plural': 'Histórico de Logins',
                'ordering': ['-data_hora'],
            },
        ),
    ]
