# Generated by Django 6.0.5 on 2026-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0022_historico_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaolinguagem',
            name='pont_consciencia_fono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consciência Fonológica'),
        ),
        migrations.AddField(
            model_name='avaliacaolinguagem',
            name='pont_fluencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fluência'),
        ),
    ]
