# Generated by Django 6.0.5 on 2026-05-19 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0024_alimentacao_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoalimentacao',
            name='pont_degluticao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deglutição e Segurança'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalimentacao',
            name='pont_motricidade_oral',
            field=models.IntegerField(blank=True, null=True, verbose_name='Motricidade Orofacial'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalimentacao',
            name='pont_recusa_rituais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comportamento Refeições'),
        ),
        migrations.AlterField(
            model_name='avaliacaoalimentacao',
            name='pont_sensibilidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tolerância Sensorial'),
        ),
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('psicopedagogica', 'Avaliação Psicopedagógica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='moduloavaliacao',
            name='codigo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Perfil Sensorial Bebê/Criança Pequena'), ('spm', 'SPM — Sensory Processing Measure'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('psicopedagogica', 'Avaliação Psicopedagógica')], max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='AvaliacaoHabitosOrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_respiracao', models.IntegerField(blank=True, null=True, verbose_name='Respiração Nasal')),
                ('pont_succao', models.IntegerField(blank=True, null=True, verbose_name='Sucção Não-Nutritiva')),
                ('pont_mastigacao', models.IntegerField(blank=True, null=True, verbose_name='Mastigação')),
                ('pont_degluticao', models.IntegerField(blank=True, null=True, verbose_name='Padrão de Deglutição')),
                ('pont_postura', models.IntegerField(blank=True, null=True, verbose_name='Postura e Bruxismo')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_habitos_orais', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Triagem de Hábitos Orais',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoIDV10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_comunicativo', models.IntegerField(blank=True, null=True, verbose_name='Impacto Comunicativo')),
                ('pont_fisico', models.IntegerField(blank=True, null=True, verbose_name='Aspectos Físicos')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_idv10', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'IDV-10',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoProcessamentoAuditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_atencao', models.IntegerField(blank=True, null=True, verbose_name='Atenção e Discriminação')),
                ('pont_compreensao', models.IntegerField(blank=True, null=True, verbose_name='Compreensão Auditiva')),
                ('pont_memoria', models.IntegerField(blank=True, null=True, verbose_name='Memória Auditiva')),
                ('pont_figura_fundo', models.IntegerField(blank=True, null=True, verbose_name='Figura-Fundo')),
                ('pont_impacto', models.IntegerField(blank=True, null=True, verbose_name='Impacto Funcional')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_processamento_auditivo', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Triagem de Processamento Auditivo',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoVozInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_funcional', models.IntegerField(blank=True, null=True, verbose_name='Funcional')),
                ('pont_fisico', models.IntegerField(blank=True, null=True, verbose_name='Físico')),
                ('pont_emocional', models.IntegerField(blank=True, null=True, verbose_name='Emocional')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_voz_infantil', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Triagem de Voz Infantil',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaHabitosOrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=30)),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaohabitosorais')),
            ],
            options={
                'ordering': ['dominio', 'numero_item'],
                'unique_together': {('avaliacao', 'dominio', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaIDV10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=30)),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoidv10')),
            ],
            options={
                'ordering': ['dominio', 'numero_item'],
                'unique_together': {('avaliacao', 'dominio', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaProcessamentoAuditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=30)),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoprocessamentoauditivo')),
            ],
            options={
                'ordering': ['dominio', 'numero_item'],
                'unique_together': {('avaliacao', 'dominio', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaVozInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=30)),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaovozinfantil')),
            ],
            options={
                'ordering': ['dominio', 'numero_item'],
                'unique_together': {('avaliacao', 'dominio', 'numero_item')},
            },
        ),
    ]
