# Generated by Django 6.0.5 on 2026-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0026_observacao_por_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='plano',
            field=models.CharField(choices=[('start', 'START'), ('plus', 'PLUS'), ('elite', 'ELITE')], default='start', max_length=10, verbose_name='Plano'),
        ),
    ]
