# Generated by Django 6.0.5 on 2026-05-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0027_plano_perfilmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='trial_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do trial'),
        ),
        migrations.AlterField(
            model_name='perfilmedico',
            name='plano',
            field=models.CharField(choices=[('trial', 'Grátis 7 dias'), ('start', 'START'), ('plus', 'PLUS'), ('elite', 'ELITE')], default='trial', max_length=10, verbose_name='Plano'),
        ),
    ]
