# Generated by Django 4.2.11 on 2026-05-27 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionario', '0030_fix_uuid_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('start', 'START — R$ 39,90/mês'), ('plus', 'PLUS — R$ 79,90/mês'), ('elite', 'ELITE — R$ 149,90/mês')], max_length=10, verbose_name='Plano solicitado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=12, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do usuário')),
                ('nota_admin', models.TextField(blank=True, verbose_name='Nota do admin')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado/Rejeitado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_plano', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Plano',
                'verbose_name_plural': 'Solicitações de Plano',
                'ordering': ['-criado_em'],
            },
        ),
    ]
