# Generated by Django 4.2.11 on 2026-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0031_solicitacao_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='plano_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do plano'),
        ),
    ]
