# Generated by Django 4.2.11 on 2026-05-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0033_painelpagamentos_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelRecebimento',
            fields=[
            ],
            options={
                'verbose_name': 'Painel de Recebimento',
                'verbose_name_plural': 'Painel de Recebimento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('questionario.solicitacaoplano',),
        ),
    ]
