# Generated by Django 6.0.5 on 2026-05-29 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0036_popular_novos_modulos_psicologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAQ10Adulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Total (0–10)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_aq10_adulto', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'AQ-10 Adulto — Rastreio de Autismo',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoAQ10Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Total (0–10)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_aq10_child', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'AQ-10 Criança — Rastreio de Autismo',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoBAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Total (0–63)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_bai', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'BAI — Inventário de Ansiedade de Beck',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoBDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Total (0–63)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_bdi', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'BDI — Inventário de Depressão de Beck',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoBSL23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('media_total', models.FloatField(blank=True, null=True, verbose_name='Média Total (0–4)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_bsl23', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'BSL-23 — Sintomas Borderline',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDASS21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_depressao', models.IntegerField(blank=True, null=True, verbose_name='Depressão (0–42)')),
                ('pont_ansiedade', models.IntegerField(blank=True, null=True, verbose_name='Ansiedade (0–42)')),
                ('pont_estresse', models.IntegerField(blank=True, null=True, verbose_name='Estresse (0–42)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_dass21', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'DASS-21 — Depressão, Ansiedade e Estresse',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDepEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_ansiedade_separacao', models.IntegerField(blank=True, null=True, verbose_name='Ansiedade de Separação')),
                ('pont_expressao_afetiva', models.IntegerField(blank=True, null=True, verbose_name='Expressão Afetiva')),
                ('pont_modificacao_planos', models.IntegerField(blank=True, null=True, verbose_name='Modificação de Planos')),
                ('pont_miedo_soledad', models.IntegerField(blank=True, null=True, verbose_name='Medo da Solidão')),
                ('pont_expresion_limite', models.IntegerField(blank=True, null=True, verbose_name='Expressão Limite')),
                ('pont_busqueda_atencion', models.IntegerField(blank=True, null=True, verbose_name='Busca de Atenção')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_dep_emocional', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Dependência Emocional',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoHAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_ansiedade', models.IntegerField(blank=True, null=True, verbose_name='Ansiedade (0–21)')),
                ('pont_depressao', models.IntegerField(blank=True, null=True, verbose_name='Depressão (0–21)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_had', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'HAD — Ansiedade e Depressão Hospitalar',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoSCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Total (0–40)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_scq', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'SCQ — Comunicação Social',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAQ10Adulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoaq10adulto')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaAQ10Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoaq10child')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaBAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaobai')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaBDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaobdi')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaBSL23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaobsl23')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaDASS21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaodass21')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaDepEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaodepemocional')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaHAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaohad')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaSCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoscq')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
