# Generated by Django 6.0.5 on 2026-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0039_add_denver_qmpi_dislexia_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoanamneseadulto',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='avaliacaoanamnesetdahadulto',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='avaliacaoanamnesetdahinf',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='avaliacaoanamneseteainf',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
