# Generated by Django 6.0.5 on 2026-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0040_add_token_anamneses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoanamnesetdahadulto',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='avaliacaoanamnesetdahinf',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='avaliacaoanamneseteainf',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='moduloavaliacao',
            name='codigo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Perfil Sensorial Bebê/Criança Pequena'), ('spm', 'SPM — Sensory Processing Measure'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos')], max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.DeleteModel(
            name='AvaliacaoAnamneseAdulto',
        ),
        migrations.DeleteModel(
            name='AvaliacaoAnamneseTDAHAdulto',
        ),
        migrations.DeleteModel(
            name='AvaliacaoAnamneseTDAHInf',
        ),
        migrations.DeleteModel(
            name='AvaliacaoAnamneseTEAInf',
        ),
    ]
