# Generated by Django 6.0.5 on 2026-06-08 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0047_add_novos_tipos_linkconvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('recompensa_aplicada', models.BooleanField(default=False, verbose_name='Recompensa aplicada')),
                ('recompensa_aplicada_em', models.DateTimeField(blank=True, null=True, verbose_name='Recompensa aplicada em')),
                ('indicado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicacao_origem', to=settings.AUTH_USER_MODEL, verbose_name='Profissional indicado')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Indicado por')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
