# Generated by Django 6.0.5 on 2026-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0049_perfilmedico_codigo_indicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='tipo_conta',
            field=models.CharField(choices=[('profissional', 'Profissional autônomo'), ('clinica', 'Clínica / Equipe')], default='profissional', max_length=15, verbose_name='Tipo de conta'),
        ),
    ]
