# Generated by Django 6.0.5 on 2026-06-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0050_add_tipo_conta_perfilmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaportage',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
