# Generated by Django 6.0.5 on 2026-06-18 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0051_add_observacao_resposta_portage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='codigo',
            field=models.CharField(choices=[('terapeuta_ocupacional', 'Terapia Ocupacional'), ('psicologo', 'Psicologia'), ('fonoaudiologo', 'Fonoaudiologia'), ('neuropsicoplogo', 'Neuropsicologia'), ('psicopedagogo', 'Psicopedagogia'), ('pediatra', 'Pediatria'), ('neuropediatra', 'Neuropediatria'), ('analista_aba', 'ABA / Análise do Comportamento'), ('nutricionista', 'Nutrição')], max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos'), ('phq9', 'PHQ-9 — Questionário de Saúde do Paciente'), ('gad7', 'GAD-7 — Transtorno de Ansiedade Generalizada'), ('epds', 'EPDS — Depressão Pós-Parto de Edinburgh'), ('pcl5', 'PCL-5 — Lista de Verificação de PTSD'), ('ghq12', 'GHQ-12 — Questionário de Saúde Geral'), ('k10', 'K-10 — Escala de Kessler'), ('ucla', 'UCLA — Escala de Solidão'), ('msi_bpd', 'MSI-BPD — Triagem de Borderline'), ('gds15', 'GDS-15 — Depressão Geriátrica'), ('rosenberg', 'Rosenberg — Autoestima'), ('audit', 'AUDIT — Uso de Álcool'), ('bis11', 'BIS-11 — Impulsividade de Barratt'), ('hama', 'HAM-A — Ansiedade de Hamilton'), ('lsas', 'LSAS — Ansiedade Social de Liebowitz'), ('risco_suicidio', 'Triagem de Risco de Suicídio'), ('agorafobia', 'Rastreio de Agorafobia'), ('panico', 'Rastreio de Pânico'), ('iar', 'IAR — Ansiedade Infantil'), ('pas', 'PAS — Ansiedade Pré-Escolar'), ('cdi', 'CDI — Depressão Infantil'), ('recordatorio_alimentar', 'Recordatório Alimentar (Pais)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='moduloavaliacao',
            name='codigo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Perfil Sensorial Bebê/Criança Pequena'), ('spm', 'SPM — Sensory Processing Measure'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('k10', 'K-10 — Escala de Kessler'), ('ucla', 'UCLA — Escala de Solidão'), ('msi_bpd', 'MSI-BPD — Triagem de Borderline'), ('gds15', 'GDS-15 — Depressão Geriátrica'), ('rosenberg', 'Rosenberg — Autoestima'), ('audit', 'AUDIT — Uso de Álcool'), ('bis11', 'BIS-11 — Impulsividade de Barratt'), ('iar', 'IAR — Ansiedade Infantil'), ('pas', 'PAS — Ansiedade Pré-Escolar'), ('cdi', 'CDI — Depressão Infantil'), ('hama', 'HAM-A — Ansiedade de Hamilton'), ('lsas', 'LSAS — Ansiedade Social de Liebowitz'), ('risco_suicidio', 'Triagem de Risco de Suicídio'), ('agorafobia', 'Rastreio de Agorafobia'), ('panico', 'Rastreio de Pânico'), ('phq9', 'PHQ-9 — Questionário de Saúde do Paciente'), ('gad7', 'GAD-7 — Transtorno de Ansiedade Generalizada'), ('epds', 'EPDS — Depressão Pós-Parto de Edinburgh'), ('pcl5', 'PCL-5 — Lista de Verificação de PTSD'), ('ghq12', 'GHQ-12 — Questionário de Saúde Geral'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos'), ('recordatorio_alimentar', 'Recordatório Alimentar (3 dias)'), ('anamnese_alimentar', 'Anamnese Alimentar')], max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='AvaliacaoAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('hist_alergia', models.BooleanField(default=False)),
                ('hist_refluxo', models.BooleanField(default=False)),
                ('hist_prob_gi', models.BooleanField(default=False)),
                ('hist_dif_respiratoria', models.BooleanField(default=False)),
                ('hist_baixo_peso', models.BooleanField(default=False)),
                ('hist_prematuridade', models.BooleanField(default=False)),
                ('hist_tonus', models.BooleanField(default=False)),
                ('hist_explane', models.TextField(blank=True, default='')),
                ('func_amamentacao', models.BooleanField(default=False)),
                ('func_mamadeira', models.BooleanField(default=False)),
                ('func_papinhas', models.BooleanField(default=False)),
                ('func_solidos', models.BooleanField(default=False)),
                ('func_maos', models.BooleanField(default=False)),
                ('func_utensilios', models.BooleanField(default=False)),
                ('func_copo', models.BooleanField(default=False)),
                ('func_explane', models.TextField(blank=True, default='')),
                ('historico_declinio', models.TextField(blank=True, default='')),
                ('sens_visual_forma', models.TextField(blank=True, default='')),
                ('sens_visual_cor', models.TextField(blank=True, default='')),
                ('sens_visual_tamanho', models.TextField(blank=True, default='')),
                ('sens_visual_outros', models.TextField(blank=True, default='')),
                ('sens_olfato_pouco', models.TextField(blank=True, default='')),
                ('sens_olfato_intenso', models.TextField(blank=True, default='')),
                ('sens_olfato_nao_importa', models.TextField(blank=True, default='')),
                ('sens_olfato_outros', models.TextField(blank=True, default='')),
                ('sens_tato_frio', models.TextField(blank=True, default='')),
                ('sens_tato_quente', models.TextField(blank=True, default='')),
                ('sens_tato_morno', models.TextField(blank=True, default='')),
                ('sens_tato_mole', models.TextField(blank=True, default='')),
                ('sens_tato_dura', models.TextField(blank=True, default='')),
                ('sens_tato_semi_dura', models.TextField(blank=True, default='')),
                ('sens_tato_liso', models.TextField(blank=True, default='')),
                ('sens_tato_rugoso', models.TextField(blank=True, default='')),
                ('sens_tato_aspero', models.TextField(blank=True, default='')),
                ('sens_tato_pegajoso', models.TextField(blank=True, default='')),
                ('sens_tato_seco', models.TextField(blank=True, default='')),
                ('sens_tato_umido', models.TextField(blank=True, default='')),
                ('sens_propr_complexos', models.TextField(blank=True, default='')),
                ('sens_propr_simples', models.TextField(blank=True, default='')),
                ('sens_propr_forca', models.TextField(blank=True, default='')),
                ('sens_propr_resistencia', models.TextField(blank=True, default='')),
                ('sens_gosto_doce', models.TextField(blank=True, default='')),
                ('sens_gosto_salgado', models.TextField(blank=True, default='')),
                ('sens_gosto_amargo', models.TextField(blank=True, default='')),
                ('sens_gosto_acido', models.TextField(blank=True, default='')),
                ('sens_gosto_umami', models.TextField(blank=True, default='')),
                ('sens_audit_barulho', models.TextField(blank=True, default='')),
                ('sens_audit_crocante', models.TextField(blank=True, default='')),
                ('sens_audit_silencioso', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações clínicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_anamnese', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Anamnese Alimentar',
                'verbose_name_plural': 'Anamneses Alimentares',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações clínicas')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recordatorio', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Recordatório Alimentar',
                'verbose_name_plural': 'Recordatórios Alimentares',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recusado', 'Deixou de comer'), ('familiar', 'Cardápio familiar'), ('aceito', 'Come atualmente')], max_length=10)),
                ('ordem', models.IntegerField(default=0)),
                ('alimento', models.CharField(blank=True, default='', max_length=200)),
                ('preparo', models.TextField(blank=True, default='')),
                ('horario', models.CharField(blank=True, default='', max_length=50)),
                ('observacao', models.TextField(blank=True, default='')),
                ('tempo', models.CharField(blank=True, default='', max_length=100)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='questionario.avaliacaorecordatorio')),
            ],
            options={
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='EntradaRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Dia 1 — semana'), ('2', 'Dia 2 — semana'), ('3', 'Dia 3 — fim de semana')], max_length=1)),
                ('refeicao', models.CharField(choices=[('cafe', 'Café da manhã'), ('lanche_manha', 'Lanche da manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da tarde'), ('jantar', 'Jantar'), ('ceia', 'Ceia'), ('entre_refeicoes', 'Entre refeições')], max_length=20)),
                ('horario', models.CharField(blank=True, default='', max_length=20)),
                ('o_que_comeu', models.TextField(blank=True, default='')),
                ('onde', models.CharField(blank=True, default='', max_length=100)),
                ('com_quem', models.CharField(blank=True, default='', max_length=100)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='questionario.avaliacaorecordatorio')),
            ],
            options={
                'ordering': ['dia', 'refeicao'],
                'unique_together': {('avaliacao', 'dia', 'refeicao')},
            },
        ),
    ]
