# Generated by Django 6.0.5 on 2026-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0052_alter_especialidade_codigo_alter_linkconvite_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('landing', 'Landing Page (/)'), ('login', 'Login (/login/)'), ('cadastro', 'Cadastro (/registrar/)')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='', max_length=500)),
                ('visitado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visita de Página',
                'verbose_name_plural': 'Visitas de Páginas',
                'ordering': ['-visitado_em'],
            },
        ),
    ]
