# Generated by Django 6.0.5 on 2026-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0053_add_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='pagina',
            field=models.CharField(choices=[('landing', 'Landing Page (/)'), ('login', 'Login (/login/)'), ('cadastro', 'Cadastro (/registrar/)'), ('instrumentos', 'Instrumentos (/instrumentos/)'), ('privacidade', 'Privacidade (/privacidade/)'), ('contato', 'Contato (/contato/)'), ('planos', 'Planos (/planos/)')], max_length=20),
        ),
    ]
