# Generated by Django 6.0.5 on 2026-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0054_alter_pagevisit_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmedico',
            name='token_confirmacao',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token de confirmação de e-mail'),
        ),
    ]
