# Generated by Django 6.0.5 on 2026-06-22 00:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0055_add_token_confirmacao_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEBAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_bruto', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Bruta (14–98)')),
                ('escore_t', models.IntegerField(blank=True, null=True, verbose_name='Escore T')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_ebai', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'EBAI — Escala Brasileira de Alimentação Infantil',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoECA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_mastigacao', models.IntegerField(blank=True, null=True, verbose_name='Motricidade na Mastigação')),
                ('pont_seletividade', models.IntegerField(blank=True, null=True, verbose_name='Seletividade Alimentar')),
                ('pont_comportamental', models.IntegerField(blank=True, null=True, verbose_name='Aspectos Comportamentais')),
                ('pont_gi', models.IntegerField(blank=True, null=True, verbose_name='Sintomas Gastrointestinais')),
                ('pont_sensorial', models.IntegerField(blank=True, null=True, verbose_name='Sensibilidade Sensorial')),
                ('pont_habilidades', models.IntegerField(blank=True, null=True, verbose_name='Habilidades nas Refeições')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_eca', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'ECA — Escala de Avaliação do Comportamento Alimentar',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoSEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_aversao_toque', models.IntegerField(blank=True, null=True, verbose_name='Aversão ao toque da comida (0–16)')),
                ('pont_foco_unica', models.IntegerField(blank=True, null=True, verbose_name='Foco numa única comida (0–16)')),
                ('pont_vomito', models.IntegerField(blank=True, null=True, verbose_name='Vômito (0–16)')),
                ('pont_sensib_temp', models.IntegerField(blank=True, null=True, verbose_name='Sensibilidade à temperatura (0–16)')),
                ('pont_expulsao', models.IntegerField(blank=True, null=True, verbose_name='Expulsão (0–12)')),
                ('pont_encher', models.IntegerField(blank=True, null=True, verbose_name='Encher demasiado (0–12)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_seps', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'SEPS — Escala de Problemas Sensoriais na Alimentação',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoTOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Pontuação Total (0–135)')),
                ('itens_corte_positivos', models.IntegerField(blank=True, null=True, verbose_name='Itens de corte positivos (≥2)')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_tod', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'TOD — Escala de Avaliação de Comportamentos Disruptivos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaEBAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoebai')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaECA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoeca')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaSEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoseps')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaTOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaotod')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
