# Generated by Django 6.0.5 on 2026-06-22 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0057_add_ebai_seps_eca_tod_to_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('impacto', models.CharField(choices=[('none', 'Sem Impacto'), ('minor', 'Impacto Menor'), ('major', 'Impacto Maior'), ('critical', 'Crítico'), ('maintenance', 'Manutenção Programada')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('investigating', 'Investigando'), ('identified', 'Identificado'), ('monitoring', 'Monitorando'), ('resolved', 'Resolvido'), ('scheduled', 'Agendado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='investigating', max_length=20)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incidente / Manutenção',
                'verbose_name_plural': 'Incidentes / Manutenções',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
