# Generated by Django 6.0.5 on 2026-06-24 19:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0058_status_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('proade', 'PROADE — Avaliação do Desempenho Escolar'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos'), ('phq9', 'PHQ-9 — Questionário de Saúde do Paciente'), ('gad7', 'GAD-7 — Transtorno de Ansiedade Generalizada'), ('epds', 'EPDS — Depressão Pós-Parto de Edinburgh'), ('pcl5', 'PCL-5 — Lista de Verificação de PTSD'), ('ghq12', 'GHQ-12 — Questionário de Saúde Geral'), ('k10', 'K-10 — Escala de Kessler'), ('ucla', 'UCLA — Escala de Solidão'), ('msi_bpd', 'MSI-BPD — Triagem de Borderline'), ('gds15', 'GDS-15 — Depressão Geriátrica'), ('rosenberg', 'Rosenberg — Autoestima'), ('audit', 'AUDIT — Uso de Álcool'), ('bis11', 'BIS-11 — Impulsividade de Barratt'), ('hama', 'HAM-A — Ansiedade de Hamilton'), ('lsas', 'LSAS — Ansiedade Social de Liebowitz'), ('risco_suicidio', 'Triagem de Risco de Suicídio'), ('agorafobia', 'Rastreio de Agorafobia'), ('panico', 'Rastreio de Pânico'), ('iar', 'IAR — Ansiedade Infantil'), ('pas', 'PAS — Ansiedade Pré-Escolar'), ('cdi', 'CDI — Depressão Infantil'), ('recordatorio_alimentar', 'Recordatório Alimentar (Pais)'), ('ebai', 'EBAI — Escala Brasileira de Alimentação Infantil'), ('seps', 'SEPS — Escala de Problemas Sensoriais na Alimentação'), ('eca', 'ECA — Avaliação do Comportamento Alimentar'), ('tod', 'TOD — Escala de Comportamentos Disruptivos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='moduloavaliacao',
            name='codigo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Perfil Sensorial Bebê/Criança Pequena'), ('spm', 'SPM — Sensory Processing Measure'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('k10', 'K-10 — Escala de Kessler'), ('ucla', 'UCLA — Escala de Solidão'), ('msi_bpd', 'MSI-BPD — Triagem de Borderline'), ('gds15', 'GDS-15 — Depressão Geriátrica'), ('rosenberg', 'Rosenberg — Autoestima'), ('audit', 'AUDIT — Uso de Álcool'), ('bis11', 'BIS-11 — Impulsividade de Barratt'), ('iar', 'IAR — Ansiedade Infantil'), ('proade', 'PROADE — Avaliação do Desempenho Escolar'), ('pas', 'PAS — Ansiedade Pré-Escolar'), ('cdi', 'CDI — Depressão Infantil'), ('hama', 'HAM-A — Ansiedade de Hamilton'), ('lsas', 'LSAS — Ansiedade Social de Liebowitz'), ('risco_suicidio', 'Triagem de Risco de Suicídio'), ('agorafobia', 'Rastreio de Agorafobia'), ('panico', 'Rastreio de Pânico'), ('phq9', 'PHQ-9 — Questionário de Saúde do Paciente'), ('gad7', 'GAD-7 — Transtorno de Ansiedade Generalizada'), ('epds', 'EPDS — Depressão Pós-Parto de Edinburgh'), ('pcl5', 'PCL-5 — Lista de Verificação de PTSD'), ('ghq12', 'GHQ-12 — Questionário de Saúde Geral'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos'), ('recordatorio_alimentar', 'Recordatório Alimentar (3 dias)'), ('anamnese_alimentar', 'Anamnese Alimentar'), ('ebai', 'EBAI — Escala Brasileira de Alimentação Infantil'), ('seps', 'SEPS — Escala de Problemas Sensoriais na Alimentação'), ('eca', 'ECA — Escala de Avaliação do Comportamento Alimentar'), ('tod', 'TOD — Escala de Comportamentos Disruptivos')], max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='AvaliacaoProade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('ano_escolar', models.IntegerField(choices=[(1, '1º ano'), (2, '2º ano'), (3, '3º ano'), (4, '4º ano'), (5, '5º ano')], default=1, verbose_name='Ano escolar')),
                ('pagina_atual', models.IntegerField(default=1)),
                ('pont_linguagem_oral', models.IntegerField(blank=True, null=True, verbose_name='Linguagem Oral')),
                ('pont_leitura', models.IntegerField(blank=True, null=True, verbose_name='Leitura')),
                ('pont_escrita', models.IntegerField(blank=True, null=True, verbose_name='Escrita')),
                ('pont_matematica', models.IntegerField(blank=True, null=True, verbose_name='Matemática')),
                ('pont_psicossocial', models.IntegerField(blank=True, null=True, verbose_name='Aspectos Psicossociais')),
                ('pont_total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_proade', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'PROADE — Avaliação do Desempenho Escolar',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaProade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoproade')),
            ],
            options={
                'ordering': ['area', 'numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
