# Generated by Django 6.0.5 on 2026-06-28 22:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0059_add_proade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAdultoSensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pont_baixo_registro', models.IntegerField(blank=True, null=True, verbose_name='Baixo Registro')),
                ('pont_procura_sensacao', models.IntegerField(blank=True, null=True, verbose_name='Procura Sensação')),
                ('pont_sensitividade', models.IntegerField(blank=True, null=True, verbose_name='Sensitividade Sensorial')),
                ('pont_evita_sensacao', models.IntegerField(blank=True, null=True, verbose_name='Evita Sensação')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_adulto_sensorial', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Perfil Sensorial do Adulto',
                'verbose_name_plural': 'Perfis Sensoriais do Adulto',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoPS2Bebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('faixa', models.CharField(choices=[('bebe', 'PS2 Bebê (0–6 meses)'), ('cp', 'PS2 Criança Pequena (7–35 meses)')], max_length=5)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da avaliação')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='em_andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pont_geral', models.IntegerField(blank=True, null=True)),
                ('pont_auditivo', models.IntegerField(blank=True, null=True)),
                ('pont_visual', models.IntegerField(blank=True, null=True)),
                ('pont_tato', models.IntegerField(blank=True, null=True)),
                ('pont_movimentos', models.IntegerField(blank=True, null=True)),
                ('pont_oral', models.IntegerField(blank=True, null=True)),
                ('pont_comportamental', models.IntegerField(blank=True, null=True)),
                ('pont_ex', models.IntegerField(blank=True, null=True)),
                ('pont_ev', models.IntegerField(blank=True, null=True)),
                ('pont_sn', models.IntegerField(blank=True, null=True)),
                ('pont_ob', models.IntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_ps2_bebe', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'PS2 Bebê/Criança Pequena (Winnie Dunn)',
                'verbose_name_plural': 'PS2 Bebê/Criança Pequena (Winnie Dunn)',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAdultoSensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaoadultosensorial')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='RespostaPS2Bebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.avaliacaops2bebe')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('avaliacao', 'numero_item')},
            },
        ),
    ]
