# Generated by Django 6.0.5 on 2026-06-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0060_ps2_bebe_adulto_sensorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoadultosensorial',
            name='pagina_atual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='avaliacaoadultosensorial',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='avaliacaops2bebe',
            name='pagina_atual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='avaliacaops2bebe',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='linkconvite',
            name='tipo',
            field=models.CharField(choices=[('sensorial', 'Perfil Sensorial'), ('vineland', 'Escala Vineland'), ('escolar', 'Questionário Sensorial Escolar'), ('bebe', 'Bebê (0–6 meses)'), ('crianca_pequena', 'Criança Pequena (7–36 meses)'), ('spm_p', 'SPM-P Casa (2–5 anos)'), ('spm_casa', 'SPM Casa (5–12 anos)'), ('ps2_bebe_wd', 'PS2 Bebê — Perfil Sensorial 2 (0–6 meses)'), ('ps2_cp_wd', 'PS2 Criança Pequena — Perfil Sensorial 2 (7–35 meses)'), ('adulto_sensorial', 'Perfil Sensorial do Adulto/Adolescente'), ('edm', 'EDM Figueiredo'), ('mabc2', 'MABC-2'), ('beery', 'Beery VMI'), ('pedi', 'PEDI'), ('vineland3', 'Vineland-3'), ('portage', 'Guia Portage'), ('sdq', 'SDQ — Capacidades e Dificuldades'), ('snap_iv', 'SNAP-IV — Avaliação de TDAH/TOD'), ('mchat', 'M-CHAT-R — Rastreio de Autismo'), ('cars', 'CARS-2 — Escala de Autismo em Crianças'), ('conners_pais', 'Conners-3 — Avaliação TDAH (Pais)'), ('etdah_pais', 'ETDAH — Avaliação TDAH (Pais)'), ('auqei', 'AUQEI — Qualidade de Vida Infantil'), ('aq10_child', 'AQ-10 Criança — Rastreio de Autismo'), ('scared', 'SCARED — Ansiedade Infantil (Pais)'), ('masc', 'MASC — Ansiedade Multidimensional'), ('scq', 'SCQ — Comunicação Social'), ('conners_prof', 'Conners-3 — Avaliação TDAH (Professor)'), ('etdah_prof', 'ETDAH — Avaliação TDAH (Professor)'), ('bdi', 'BDI — Inventário de Depressão de Beck'), ('bai', 'BAI — Inventário de Ansiedade de Beck'), ('dass21', 'DASS-21 — Depressão, Ansiedade e Estresse'), ('had', 'HAD — Ansiedade e Depressão Hospitalar'), ('bsl23', 'BSL-23 — Sintomas Borderline'), ('aq10_adulto', 'AQ-10 Adulto — Rastreio de Autismo'), ('dep_emocional', 'Questionário de Dependência Emocional'), ('bpq', 'BPQ — Personalidade Borderline'), ('linguagem', 'Avaliação de Linguagem'), ('alimentacao_seletiva', 'Triagem de Alimentação Seletiva'), ('habitos_orais', 'Hábitos Orais Deletérios'), ('voz_infantil', 'Triagem de Voz Infantil (pVHI)'), ('processamento_auditivo', 'Triagem de Processamento Auditivo'), ('idv10', 'IDV-10 — Índice de Desvantagem Vocal'), ('desenvolvimento', 'Marcos de Desenvolvimento Infantil'), ('sono_infantil', 'Avaliação de Sono Infantil'), ('denver', 'Checklist Denver II — Desenvolvimento'), ('habilidades_adaptativas', 'Habilidades Adaptativas (ABA)'), ('comportamento_funcional', 'Comportamento Funcional (ABA)'), ('rastreio_cognitivo', 'Rastreio Cognitivo'), ('qmpi', 'QMPI — Memória Prospectiva Infantil'), ('psicopedagogica', 'Avaliação Psicopedagógica'), ('proade', 'PROADE — Avaliação do Desempenho Escolar'), ('quest_dislexia', 'Questionário de Dislexia (Pais)'), ('checklist_dislexia', 'Checklist de Dislexia'), ('prot_dislexia_prof', 'Protocolo Dislexia — Avaliação Escolar'), ('inventario_dislexia', 'Inventário de Sinais Disléxicos'), ('phq9', 'PHQ-9 — Questionário de Saúde do Paciente'), ('gad7', 'GAD-7 — Transtorno de Ansiedade Generalizada'), ('epds', 'EPDS — Depressão Pós-Parto de Edinburgh'), ('pcl5', 'PCL-5 — Lista de Verificação de PTSD'), ('ghq12', 'GHQ-12 — Questionário de Saúde Geral'), ('k10', 'K-10 — Escala de Kessler'), ('ucla', 'UCLA — Escala de Solidão'), ('msi_bpd', 'MSI-BPD — Triagem de Borderline'), ('gds15', 'GDS-15 — Depressão Geriátrica'), ('rosenberg', 'Rosenberg — Autoestima'), ('audit', 'AUDIT — Uso de Álcool'), ('bis11', 'BIS-11 — Impulsividade de Barratt'), ('hama', 'HAM-A — Ansiedade de Hamilton'), ('lsas', 'LSAS — Ansiedade Social de Liebowitz'), ('risco_suicidio', 'Triagem de Risco de Suicídio'), ('agorafobia', 'Rastreio de Agorafobia'), ('panico', 'Rastreio de Pânico'), ('iar', 'IAR — Ansiedade Infantil'), ('pas', 'PAS — Ansiedade Pré-Escolar'), ('cdi', 'CDI — Depressão Infantil'), ('recordatorio_alimentar', 'Recordatório Alimentar (Pais)'), ('ebai', 'EBAI — Escala Brasileira de Alimentação Infantil'), ('seps', 'SEPS — Escala de Problemas Sensoriais na Alimentação'), ('eca', 'ECA — Avaliação do Comportamento Alimentar'), ('tod', 'TOD — Escala de Comportamentos Disruptivos')], max_length=30),
        ),
    ]
