# Generated by Django 6.0.5 on 2026-06-03 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionario', '0042_denver_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('anamnese', 'Anamnese'), ('ficha_triagem', 'Ficha de Triagem'), ('carta_encaminhamento', 'Carta de Encaminhamento'), ('atestado', 'Atestado'), ('relatorio', 'Relatório')], max_length=30)),
                ('conteudo', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='questionario.paciente')),
            ],
            options={
                'verbose_name': 'Procedimento / Documento',
                'verbose_name_plural': 'Procedimentos / Documentos',
                'unique_together': {('paciente', 'tipo')},
            },
        ),
    ]
