# Generated by Django 6.0.5 on 2026-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimentodocumento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Procedimento / Documento', 'verbose_name_plural': 'Procedimentos / Documentos'},
        ),
        migrations.AlterUniqueTogether(
            name='procedimentodocumento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='procedimentodocumento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
    ]
