# Generated by Django 6.0.5 on 2026-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0003_alter_procedimentodocumento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentodocumento',
            name='tipo',
            field=models.CharField(choices=[('anamnese', 'Anamnese Geral'), ('anamnese_adulto', 'Anamnese — Adulto'), ('anamnese_infantil', 'Anamnese — Infantil / Adolescente'), ('anamnese_tea', 'Anamnese — TEA / Autismo'), ('anamnese_tdah', 'Anamnese — TDAH'), ('anamnese_casal', 'Anamnese — Casal'), ('anamnese_seletividade_alimentar', 'Anamnese — Seletividade Alimentar'), ('ficha_triagem', 'Ficha de Triagem'), ('carta_encaminhamento', 'Carta de Encaminhamento'), ('atestado', 'Atestado'), ('relatorio', 'Relatório')], max_length=40),
        ),
    ]
