# Generated by Django 6.0.5 on 2026-06-30 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0004_add_anamnese_seletividade_alimentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentodocumento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do registro'),
        ),
        migrations.AddField(
            model_name='procedimentodocumento',
            name='token_publico',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='procedimentodocumento',
            name='tipo',
            field=models.CharField(choices=[('anamnese', 'Anamnese Geral'), ('anamnese_adulto', 'Anamnese — Adulto'), ('anamnese_infantil', 'Anamnese — Infantil / Adolescente'), ('anamnese_tea', 'Anamnese — TEA / Autismo'), ('anamnese_tdah', 'Anamnese — TDAH'), ('anamnese_casal', 'Anamnese — Casal'), ('anamnese_seletividade_alimentar', 'Anamnese — Seletividade Alimentar'), ('evolucao_semanal', 'Evolução de Atendimento'), ('ficha_visita_escolar', 'Ficha de Visita Escolar'), ('ficha_triagem', 'Ficha de Triagem'), ('carta_encaminhamento', 'Carta de Encaminhamento'), ('atestado', 'Atestado'), ('relatorio', 'Relatório')], max_length=40),
        ),
    ]
