server {
    listen 80;
    server_name integramente.pro www.integramente.pro;

    location /static/ {
        alias /root/perfil_sensorial/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
