from django.conf import settings
from django.shortcuts import render
from django.urls import path
from . import views

urlpatterns = [
    # Link de Convite (gerado pelo médico, preenchido pelo paciente)
    path("gerar-link/", views.gerar_link, name="gerar_link"),
    path("gerar-link/enviar-email/", views.enviar_email_convite, name="enviar_email_convite"),
    path("iniciar/<uuid:token>/", views.iniciar_avaliacao, name="iniciar_avaliacao"),
    # Auth
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("registrar/", views.registrar_view, name="registrar"),
    path("confirmar-email/<uidb64>/<token>/", views.confirmar_email_view, name="confirmar_email"),
    path("meu-perfil/", views.meu_perfil, name="meu_perfil"),
    path("privacidade/", views.politica_privacidade, name="politica_privacidade"),
    # Pagamentos (fluxo manual com PIX) — painel gerenciado pelo admin Django
    path("planos/", views.solicitar_plano, name="solicitar_plano"),
    # App
    path("", views.index, name="index"),
    path("avaliacoes/pendentes/", views.avaliacoes_pendentes, name="avaliacoes_pendentes"),
    path("pacientes/", views.lista_pacientes, name="lista_pacientes"),
    path("pacientes/novo/", views.novo_paciente, name="novo_paciente"),
    path("pacientes/<uuid:paciente_id>/", views.detalhe_paciente, name="detalhe_paciente"),
    path("pacientes/<uuid:paciente_id>/nova-avaliacao/", views.nova_avaliacao, name="nova_avaliacao"),
    path("avaliacao/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.questionario_view, name="questionario"),
    path("questionario/publico/<str:token>/<int:pagina>/", views.questionario_publico_view, name="questionario_publico"),
    path("avaliacao/<uuid:avaliacao_id>/concluir/", views.concluir, name="concluir"),
    path("avaliacao/<uuid:avaliacao_id>/dashboard/", views.dashboard, name="dashboard"),
    path("avaliacao/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.questionario_visualizar, name="questionario_visualizar"),
    path("avaliacao/<uuid:avaliacao_id>/deletar/", views.deletar_avaliacao, name="deletar_avaliacao"),
    path("avaliacao/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_link, name="enviar_email_link"),
    path("avaliacao/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes, name="salvar_observacoes"),
    path("avaliacao/<uuid:avaliacao_id>/laudo/", views.laudo_sensorial, name="laudo_sensorial"),
    path("pacientes/<uuid:paciente_id>/editar/", views.editar_paciente, name="editar_paciente"),
    path("pacientes/<uuid:paciente_id>/deletar/", views.deletar_paciente, name="deletar_paciente"),
    # Vineland
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-vineland/", views.nova_avaliacao_vineland, name="nova_avaliacao_vineland"),
    path("vineland/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.vineland_form, name="vineland_form"),
    path("vineland/<uuid:avaliacao_id>/concluir/", views.vineland_concluir, name="vineland_concluir"),
    path("vineland/<uuid:avaliacao_id>/resultado/", views.vineland_resultado, name="vineland_resultado"),
    path("vineland/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.vineland_visualizar, name="vineland_visualizar"),
    path("vineland/<uuid:avaliacao_id>/deletar/", views.vineland_deletar, name="vineland_deletar"),
    path("vineland/publico/<str:token>/<int:pagina>/", views.vineland_publico_view, name="vineland_publico"),
    path("vineland/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_link_vineland, name="enviar_email_link_vineland"),
    path("vineland/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_vineland, name="salvar_observacoes_vineland"),
    # Questionário Sensorial Escolar
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-escolar/", views.nova_avaliacao_escolar, name="nova_avaliacao_escolar"),
    path("escolar/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.escolar_form, name="escolar_form"),
    path("escolar/<uuid:avaliacao_id>/concluir/", views.escolar_concluir, name="escolar_concluir"),
    path("escolar/<uuid:avaliacao_id>/resultado/", views.escolar_resultado, name="escolar_resultado"),
    path("escolar/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.escolar_visualizar, name="escolar_visualizar"),
    path("escolar/<uuid:avaliacao_id>/deletar/", views.escolar_deletar, name="escolar_deletar"),
    path("escolar/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_escolar, name="salvar_observacoes_escolar"),
    path("escolar/publico/<str:token>/<int:pagina>/", views.escolar_publico_view, name="escolar_publico"),
    path("escolar/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_escolar, name="enviar_email_escolar"),
    # Perfil Sensorial Bebê/Criança Pequena
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bebe/", views.nova_avaliacao_bebe, name="nova_avaliacao_bebe"),
    path("bebe/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.bebe_form, name="bebe_form"),
    path("bebe/<uuid:avaliacao_id>/concluir/", views.bebe_concluir, name="bebe_concluir"),
    path("bebe/<uuid:avaliacao_id>/resultado/", views.bebe_resultado, name="bebe_resultado"),
    path("bebe/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.bebe_visualizar, name="bebe_visualizar"),
    path("bebe/<uuid:avaliacao_id>/deletar/", views.bebe_deletar, name="bebe_deletar"),
    path("bebe/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_bebe, name="salvar_observacoes_bebe"),
    path("bebe/publico/<str:token>/<int:pagina>/", views.bebe_publico_view, name="bebe_publico"),
    path("bebe/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_bebe, name="enviar_email_bebe"),
    # SPM — Sensory Processing Measure
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-spm/", views.nova_avaliacao_spm, name="nova_avaliacao_spm"),
    path("spm/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.spm_form, name="spm_form"),
    path("spm/<uuid:avaliacao_id>/concluir/", views.spm_concluir, name="spm_concluir"),
    path("spm/<uuid:avaliacao_id>/resultado/", views.spm_resultado, name="spm_resultado"),
    path("spm/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.spm_visualizar, name="spm_visualizar"),
    path("spm/<uuid:avaliacao_id>/deletar/", views.spm_deletar, name="spm_deletar"),
    path("spm/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_spm, name="salvar_observacoes_spm"),
    path("spm/publico/<str:token>/<int:pagina>/", views.spm_publico_view, name="spm_publico"),
    path("spm/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_spm, name="enviar_email_spm"),
    # EDM
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-edm/", views.nova_avaliacao_edm, name="nova_avaliacao_edm"),
    path("edm/<uuid:avaliacao_id>/", views.edm_form, name="edm_form"),
    path("edm/<uuid:avaliacao_id>/resultado/", views.edm_resultado, name="edm_resultado"),
    path("edm/<uuid:avaliacao_id>/deletar/", views.edm_deletar, name="edm_deletar"),
    path("edm/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_edm, name="salvar_observacoes_edm"),
    # MABC-2
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-mabc2/", views.nova_avaliacao_mabc2, name="nova_avaliacao_mabc2"),
    path("mabc2/<uuid:avaliacao_id>/", views.mabc2_form, name="mabc2_form"),
    path("mabc2/<uuid:avaliacao_id>/resultado/", views.mabc2_resultado, name="mabc2_resultado"),
    path("mabc2/<uuid:avaliacao_id>/deletar/", views.mabc2_deletar, name="mabc2_deletar"),
    path("mabc2/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_mabc2, name="salvar_observacoes_mabc2"),
    # Beery VMI
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-beery/", views.nova_avaliacao_beery, name="nova_avaliacao_beery"),
    path("beery/<uuid:avaliacao_id>/", views.beery_form, name="beery_form"),
    path("beery/<uuid:avaliacao_id>/resultado/", views.beery_resultado, name="beery_resultado"),
    path("beery/<uuid:avaliacao_id>/deletar/", views.beery_deletar, name="beery_deletar"),
    path("beery/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_beery, name="salvar_observacoes_beery"),
    # PEDI
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-pedi/", views.nova_avaliacao_pedi, name="nova_avaliacao_pedi"),
    path("pedi/<uuid:avaliacao_id>/", views.pedi_form, name="pedi_form"),
    path("pedi/<uuid:avaliacao_id>/resultado/", views.pedi_resultado, name="pedi_resultado"),
    path("pedi/<uuid:avaliacao_id>/deletar/", views.pedi_deletar, name="pedi_deletar"),
    path("pedi/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_pedi, name="salvar_observacoes_pedi"),
    path("pedi/<uuid:avaliacao_id>/enviar-email/", views.enviar_email_pedi, name="enviar_email_pedi"),
    path("pedi/<uuid:avaliacao_id>/visualizar/", views.pedi_visualizar, name="pedi_visualizar"),
    path("pedi/<uuid:avaliacao_id>/salvar-progresso/", views.pedi_salvar_progresso, name="pedi_salvar_progresso"),
    path("pedi/publico/<str:token>/salvar-progresso/", views.pedi_salvar_progresso_publico, name="pedi_salvar_progresso_publico"),
    path("pedi/publico/<str:token>/<int:pagina>/", views.pedi_publico, name="pedi_publico"),
    path("pedi/publico/<str:token>/", views.pedi_publico_redirect, name="pedi_publico_sem_pagina"),
    # Vineland-3
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-vineland3/", views.nova_avaliacao_vineland3, name="nova_avaliacao_vineland3"),
    path("vineland3/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.vineland3_form, name="vineland3_form"),
    path("vineland3/<uuid:avaliacao_id>/concluir/", views.vineland3_concluir, name="vineland3_concluir"),
    path("vineland3/<uuid:avaliacao_id>/resultado/", views.vineland3_resultado, name="vineland3_resultado"),
    path("vineland3/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.vineland3_visualizar, name="vineland3_visualizar"),
    path("vineland3/<uuid:avaliacao_id>/deletar/", views.vineland3_deletar, name="vineland3_deletar"),
    path("vineland3/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_vineland3, name="salvar_observacoes_vineland3"),
    path("vineland3/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_vineland3, name="enviar_email_vineland3"),
    path("vineland3/publico/<str:token>/<int:pagina>/", views.vineland3_publico_view, name="vineland3_publico"),
    # Guia Portage
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-portage/", views.nova_avaliacao_portage, name="nova_avaliacao_portage"),
    path("portage/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.portage_form, name="portage_form"),
    path("portage/<uuid:avaliacao_id>/concluir/", views.portage_concluir, name="portage_concluir"),
    path("portage/<uuid:avaliacao_id>/resultado/", views.portage_resultado, name="portage_resultado"),
    path("portage/<uuid:avaliacao_id>/deletar/", views.portage_deletar, name="portage_deletar"),
    path("portage/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.portage_visualizar, name="portage_visualizar"),
    path("portage/publico/<str:token>/<int:pagina>/", views.portage_publico_view, name="portage_publico"),
    # SDQ
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-sdq/", views.nova_avaliacao_sdq, name="nova_avaliacao_sdq"),
    path("sdq/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.sdq_form, name="sdq_form"),
    path("sdq/<uuid:avaliacao_id>/resultado/", views.sdq_resultado, name="sdq_resultado"),
    path("sdq/<uuid:avaliacao_id>/deletar/", views.sdq_deletar, name="sdq_deletar"),
    path("sdq/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_sdq, name="salvar_observacoes_sdq"),
    path("sdq/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_sdq, name="enviar_email_sdq"),
    path("sdq/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.sdq_visualizar, name="sdq_visualizar"),
    path("sdq/publico/<str:token>/<int:pagina>/", views.sdq_publico, name="sdq_publico"),
    # SNAP-IV
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-snap-iv/", views.nova_avaliacao_snap_iv, name="nova_avaliacao_snap_iv"),
    path("snap-iv/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.snap_iv_form, name="snap_iv_form"),
    path("snap-iv/<uuid:avaliacao_id>/resultado/", views.snap_iv_resultado, name="snap_iv_resultado"),
    path("snap-iv/<uuid:avaliacao_id>/deletar/", views.snap_iv_deletar, name="snap_iv_deletar"),
    path("snap-iv/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_snap_iv, name="salvar_observacoes_snap_iv"),
    path("snap-iv/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_snap_iv, name="enviar_email_snap_iv"),
    path("snap-iv/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.snap_iv_visualizar, name="snap_iv_visualizar"),
    path("snap-iv/publico/<str:token>/<int:pagina>/", views.snap_iv_publico, name="snap_iv_publico"),
    # M-CHAT-R
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-mchat/", views.nova_avaliacao_mchat, name="nova_avaliacao_mchat"),
    path("mchat/<uuid:avaliacao_id>/", views.mchat_form, name="mchat_form"),
    path("mchat/<uuid:avaliacao_id>/resultado/", views.mchat_resultado, name="mchat_resultado"),
    path("mchat/<uuid:avaliacao_id>/deletar/", views.mchat_deletar, name="mchat_deletar"),
    path("mchat/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_mchat, name="salvar_observacoes_mchat"),
    path("mchat/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_mchat, name="enviar_email_mchat"),
    path("mchat/<uuid:avaliacao_id>/visualizar/", views.mchat_visualizar, name="mchat_visualizar"),
    path("mchat/publico/<str:token>/", views.mchat_publico, name="mchat_publico"),
    # E-mail genérico para novos módulos multiprofissionais
    path("modulo/<str:modulo>/<uuid:avaliacao_id>/enviar-email/", views.enviar_email_modulo, name="enviar_email_modulo"),
    # CARS-2
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-cars/", views.nova_avaliacao_cars, name="nova_avaliacao_cars"),
    path("cars/<uuid:avaliacao_id>/", views.cars_form, name="cars_form"),
    path("cars/<uuid:avaliacao_id>/resultado/", views.cars_resultado, name="cars_resultado"),
    path("cars/<uuid:avaliacao_id>/deletar/", views.cars_deletar, name="cars_deletar"),
    path("cars/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_cars, name="salvar_observacoes_cars"),
    path("cars/<uuid:avaliacao_id>/enviar-link/", views.enviar_email_cars, name="enviar_email_cars"),
    path("cars/<uuid:avaliacao_id>/visualizar/", views.cars_visualizar, name="cars_visualizar"),
    path("cars/publico/<str:token>/", views.cars_publico, name="cars_publico"),
    # Avaliação de Linguagem
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-linguagem/", views.nova_avaliacao_linguagem, name="nova_avaliacao_linguagem"),
    path("linguagem/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.linguagem_form, name="linguagem_form"),
    path("linguagem/<uuid:avaliacao_id>/resultado/", views.linguagem_resultado, name="linguagem_resultado"),
    path("linguagem/<uuid:avaliacao_id>/deletar/", views.linguagem_deletar, name="linguagem_deletar"),
    path("linguagem/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_linguagem, name="salvar_observacoes_linguagem"),
    path("linguagem/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.linguagem_visualizar, name="linguagem_visualizar"),
    path("linguagem/publico/<str:token>/<int:pagina>/", views.linguagem_publico, name="linguagem_publico"),
    # Triagem de Alimentação
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-alimentacao/", views.nova_avaliacao_alimentacao, name="nova_avaliacao_alimentacao"),
    path("alimentacao/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.alimentacao_form, name="alimentacao_form"),
    path("alimentacao/<uuid:avaliacao_id>/resultado/", views.alimentacao_resultado, name="alimentacao_resultado"),
    path("alimentacao/<uuid:avaliacao_id>/deletar/", views.alimentacao_deletar, name="alimentacao_deletar"),
    path("alimentacao/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_alimentacao, name="salvar_observacoes_alimentacao"),
    path("alimentacao/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.alimentacao_visualizar, name="alimentacao_visualizar"),
    path("alimentacao/publico/<str:token>/<int:pagina>/", views.alimentacao_publico, name="alimentacao_publico"),
    # Hábitos Orais
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-habitos-orais/", views.nova_avaliacao_habitos_orais, name="nova_avaliacao_habitos_orais"),
    path("habitos-orais/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.habitos_orais_form, name="habitos_form"),
    path("habitos-orais/<uuid:avaliacao_id>/resultado/", views.habitos_orais_resultado, name="habitos_resultado"),
    path("habitos-orais/<uuid:avaliacao_id>/deletar/", views.habitos_orais_deletar, name="habitos_deletar"),
    path("habitos-orais/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_habitos_orais, name="salvar_observacoes_habitos_orais"),
    path("habitos-orais/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.habitos_orais_visualizar, name="habitos_visualizar"),
    path("habitos-orais/publico/<str:token>/<int:pagina>/", views.habitos_orais_publico, name="habitos_publico"),
    # Voz Infantil
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-voz-infantil/", views.nova_avaliacao_voz_infantil, name="nova_avaliacao_voz_infantil"),
    path("voz-infantil/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.voz_infantil_form, name="voz_form"),
    path("voz-infantil/<uuid:avaliacao_id>/resultado/", views.voz_infantil_resultado, name="voz_resultado"),
    path("voz-infantil/<uuid:avaliacao_id>/deletar/", views.voz_infantil_deletar, name="voz_deletar"),
    path("voz-infantil/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_voz_infantil, name="salvar_observacoes_voz_infantil"),
    path("voz-infantil/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.voz_infantil_visualizar, name="voz_visualizar"),
    path("voz-infantil/publico/<str:token>/<int:pagina>/", views.voz_infantil_publico, name="voz_publico"),
    # Processamento Auditivo
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-auditivo/", views.nova_avaliacao_processamento_auditivo, name="nova_avaliacao_processamento_auditivo"),
    path("processamento-auditivo/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.processamento_auditivo_form, name="auditivo_form"),
    path("processamento-auditivo/<uuid:avaliacao_id>/resultado/", views.processamento_auditivo_resultado, name="auditivo_resultado"),
    path("processamento-auditivo/<uuid:avaliacao_id>/deletar/", views.processamento_auditivo_deletar, name="auditivo_deletar"),
    path("processamento-auditivo/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_processamento_auditivo, name="salvar_observacoes_processamento_auditivo"),
    path("processamento-auditivo/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.processamento_auditivo_visualizar, name="auditivo_visualizar"),
    path("processamento-auditivo/publico/<str:token>/<int:pagina>/", views.processamento_auditivo_publico, name="auditivo_publico"),
    # IDV-10
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-idv10/", views.nova_avaliacao_idv10, name="nova_avaliacao_idv10"),
    path("idv10/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.idv10_form, name="idv_form"),
    path("idv10/<uuid:avaliacao_id>/resultado/", views.idv10_resultado, name="idv_resultado"),
    path("idv10/<uuid:avaliacao_id>/deletar/", views.idv10_deletar, name="idv_deletar"),
    path("idv10/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_idv10, name="salvar_observacoes_idv10"),
    path("idv10/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.idv10_visualizar, name="idv_visualizar"),
    path("idv10/publico/<str:token>/<int:pagina>/", views.idv10_publico, name="idv_publico"),
    # Marcos de Desenvolvimento
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-desenvolvimento/", views.nova_avaliacao_desenvolvimento, name="nova_avaliacao_desenvolvimento"),
    path("desenvolvimento/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.desenvolvimento_form, name="desenvolvimento_form"),
    path("desenvolvimento/<uuid:avaliacao_id>/resultado/", views.desenvolvimento_resultado, name="desenvolvimento_resultado"),
    path("desenvolvimento/<uuid:avaliacao_id>/deletar/", views.desenvolvimento_deletar, name="desenvolvimento_deletar"),
    path("desenvolvimento/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_desenvolvimento, name="salvar_observacoes_desenvolvimento"),
    path("desenvolvimento/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.desenvolvimento_visualizar, name="desenvolvimento_visualizar"),
    path("desenvolvimento/publico/<str:token>/<int:pagina>/", views.desenvolvimento_publico, name="desenvolvimento_publico"),
    # Avaliação de Sono Infantil
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-sono/", views.nova_avaliacao_sono, name="nova_avaliacao_sono"),
    path("sono/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.sono_form, name="sono_form"),
    path("sono/<uuid:avaliacao_id>/resultado/", views.sono_resultado, name="sono_resultado"),
    path("sono/<uuid:avaliacao_id>/deletar/", views.sono_deletar, name="sono_deletar"),
    path("sono/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_sono, name="salvar_observacoes_sono"),
    path("sono/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.sono_visualizar, name="sono_visualizar"),
    path("sono/publico/<str:token>/<int:pagina>/", views.sono_publico, name="sono_publico"),
    # Habilidades Adaptativas
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-habilidades/", views.nova_avaliacao_habilidades_adaptativas, name="nova_avaliacao_habilidades"),
    path("habilidades/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.habilidades_adaptativas_form, name="habilidades_form"),
    path("habilidades/<uuid:avaliacao_id>/resultado/", views.habilidades_adaptativas_resultado, name="habilidades_resultado"),
    path("habilidades/<uuid:avaliacao_id>/deletar/", views.habilidades_adaptativas_deletar, name="habilidades_deletar"),
    path("habilidades/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_habilidades_adaptativas, name="salvar_observacoes_habilidades"),
    path("habilidades/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.habilidades_adaptativas_visualizar, name="habilidades_visualizar"),
    path("habilidades/publico/<str:token>/<int:pagina>/", views.habilidades_adaptativas_publico, name="habilidades_publico"),
    # Comportamento Funcional
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-comportamento/", views.nova_avaliacao_comportamento_funcional, name="nova_avaliacao_comportamento"),
    path("comportamento/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.comportamento_funcional_form, name="comportamento_form"),
    path("comportamento/<uuid:avaliacao_id>/resultado/", views.comportamento_funcional_resultado, name="comportamento_resultado"),
    path("comportamento/<uuid:avaliacao_id>/deletar/", views.comportamento_funcional_deletar, name="comportamento_deletar"),
    path("comportamento/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_comportamento_funcional, name="salvar_observacoes_comportamento"),
    path("comportamento/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.comportamento_funcional_visualizar, name="comportamento_visualizar"),
    path("comportamento/publico/<str:token>/<int:pagina>/", views.comportamento_funcional_publico, name="comportamento_publico"),
    # Rastreio Cognitivo
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-cognitivo/", views.nova_avaliacao_cognitivo, name="nova_avaliacao_cognitivo"),
    path("cognitivo/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.cognitivo_form, name="cognitivo_form"),
    path("cognitivo/<uuid:avaliacao_id>/resultado/", views.cognitivo_resultado, name="cognitivo_resultado"),
    path("cognitivo/<uuid:avaliacao_id>/deletar/", views.cognitivo_deletar, name="cognitivo_deletar"),
    path("cognitivo/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_cognitivo, name="salvar_observacoes_cognitivo"),
    path("cognitivo/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.cognitivo_visualizar, name="cognitivo_visualizar"),
    path("cognitivo/publico/<str:token>/<int:pagina>/", views.cognitivo_publico, name="cognitivo_publico"),
    # Avaliação Psicopedagógica
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-psicopedagogica/", views.nova_avaliacao_psicopedagogica, name="nova_avaliacao_psicopedagogica"),
    path("psicopedagogica/<uuid:avaliacao_id>/pagina/<int:pagina>/", views.psicopedagogica_form, name="psicopedagogica_form"),
    path("psicopedagogica/<uuid:avaliacao_id>/resultado/", views.psicopedagogica_resultado, name="psicopedagogica_resultado"),
    path("psicopedagogica/<uuid:avaliacao_id>/deletar/", views.psicopedagogica_deletar, name="psicopedagogica_deletar"),
    path("psicopedagogica/<uuid:avaliacao_id>/observacoes/", views.salvar_observacoes_psicopedagogica, name="salvar_observacoes_psicopedagogica"),
    path("psicopedagogica/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.psicopedagogica_visualizar, name="psicopedagogica_visualizar"),
    path("psicopedagogica/publico/<str:token>/<int:pagina>/", views.psicopedagogica_publico, name="psicopedagogica_publico"),
    # ── Módulos de Psicologia ─────────────────────────────────────────────────
    # BDI — Inventário de Depressão de Beck
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bdi/",       views.nova_avaliacao_bdi,           name="nova_avaliacao_bdi"),
    path("bdi/<uuid:avaliacao_id>/pagina/<int:pagina>/",            views.bdi_form,                     name="bdi_form"),
    path("bdi/<uuid:avaliacao_id>/resultado/",                      views.bdi_resultado,                name="bdi_resultado"),
    path("bdi/<uuid:avaliacao_id>/deletar/",                        views.bdi_deletar,                  name="bdi_deletar"),
    path("bdi/<uuid:avaliacao_id>/observacoes/",                    views.salvar_observacoes_bdi,       name="salvar_observacoes_bdi"),
    path("bdi/<uuid:avaliacao_id>/visualizar/<int:pagina>/",        views.bdi_visualizar,               name="bdi_visualizar"),
    path("bdi/publico/<str:token>/<int:pagina>/",                   views.bdi_publico,                  name="bdi_publico"),
    path("bdi/<uuid:avaliacao_id>/email/",                          views.enviar_email_bdi,             name="enviar_email_bdi"),
    # K-10 — Escala de Kessler
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-k10/", views.nova_avaliacao_k10, name="nova_avaliacao_k10"),
    path("k10/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.k10_form,           name="k10_form"),
    path("k10/<uuid:avaliacao_id>/resultado/",               views.k10_resultado,      name="k10_resultado"),
    path("k10/<uuid:avaliacao_id>/deletar/",                 views.k10_deletar,        name="k10_deletar"),
    path("k10/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_k10, name="salvar_observacoes_k10"),
    path("k10/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.k10_visualizar,     name="k10_visualizar"),
    path("k10/publico/<str:token>/<int:pagina>/",            views.k10_publico,        name="k10_publico"),
    path("k10/<uuid:avaliacao_id>/email/",                   views.enviar_email_k10,   name="enviar_email_k10"),
    path("k10/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "k10"}, name="k10_laudo"),
    # UCLA — Escala de Solidão
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-ucla/", views.nova_avaliacao_ucla, name="nova_avaliacao_ucla"),
    path("ucla/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.ucla_form,           name="ucla_form"),
    path("ucla/<uuid:avaliacao_id>/resultado/",               views.ucla_resultado,      name="ucla_resultado"),
    path("ucla/<uuid:avaliacao_id>/deletar/",                 views.ucla_deletar,        name="ucla_deletar"),
    path("ucla/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_ucla, name="salvar_observacoes_ucla"),
    path("ucla/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.ucla_visualizar,     name="ucla_visualizar"),
    path("ucla/publico/<str:token>/<int:pagina>/",            views.ucla_publico,        name="ucla_publico"),
    path("ucla/<uuid:avaliacao_id>/email/",                   views.enviar_email_ucla,   name="enviar_email_ucla"),
    path("ucla/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "ucla"}, name="ucla_laudo"),
    # MSI-BPD — Triagem de Borderline
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-msi-bpd/", views.nova_avaliacao_msi_bpd, name="nova_avaliacao_msi_bpd"),
    path("msi-bpd/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.msi_bpd_form,           name="msi_bpd_form"),
    path("msi-bpd/<uuid:avaliacao_id>/resultado/",               views.msi_bpd_resultado,      name="msi_bpd_resultado"),
    path("msi-bpd/<uuid:avaliacao_id>/deletar/",                 views.msi_bpd_deletar,        name="msi_bpd_deletar"),
    path("msi-bpd/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_msi_bpd, name="salvar_observacoes_msi_bpd"),
    path("msi-bpd/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.msi_bpd_visualizar,     name="msi_bpd_visualizar"),
    path("msi-bpd/publico/<str:token>/<int:pagina>/",            views.msi_bpd_publico,        name="msi_bpd_publico"),
    path("msi-bpd/<uuid:avaliacao_id>/email/",                   views.enviar_email_msi_bpd,   name="enviar_email_msi_bpd"),
    path("msi-bpd/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "msi_bpd"}, name="msi_bpd_laudo"),
    # GDS-15 — Depressão Geriátrica
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-gds15/", views.nova_avaliacao_gds15, name="nova_avaliacao_gds15"),
    path("gds15/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.gds15_form,           name="gds15_form"),
    path("gds15/<uuid:avaliacao_id>/resultado/",               views.gds15_resultado,      name="gds15_resultado"),
    path("gds15/<uuid:avaliacao_id>/deletar/",                 views.gds15_deletar,        name="gds15_deletar"),
    path("gds15/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_gds15, name="salvar_observacoes_gds15"),
    path("gds15/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.gds15_visualizar,     name="gds15_visualizar"),
    path("gds15/publico/<str:token>/<int:pagina>/",            views.gds15_publico,        name="gds15_publico"),
    path("gds15/<uuid:avaliacao_id>/email/",                   views.enviar_email_gds15,   name="enviar_email_gds15"),
    path("gds15/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "gds15"}, name="gds15_laudo"),
    # Rosenberg — Autoestima
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-rosenberg/", views.nova_avaliacao_rosenberg, name="nova_avaliacao_rosenberg"),
    path("rosenberg/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.rosenberg_form,           name="rosenberg_form"),
    path("rosenberg/<uuid:avaliacao_id>/resultado/",               views.rosenberg_resultado,      name="rosenberg_resultado"),
    path("rosenberg/<uuid:avaliacao_id>/deletar/",                 views.rosenberg_deletar,        name="rosenberg_deletar"),
    path("rosenberg/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_rosenberg, name="salvar_observacoes_rosenberg"),
    path("rosenberg/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.rosenberg_visualizar,     name="rosenberg_visualizar"),
    path("rosenberg/publico/<str:token>/<int:pagina>/",            views.rosenberg_publico,        name="rosenberg_publico"),
    path("rosenberg/<uuid:avaliacao_id>/email/",                   views.enviar_email_rosenberg,   name="enviar_email_rosenberg"),
    path("rosenberg/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "rosenberg"}, name="rosenberg_laudo"),
    # AUDIT — Uso de Álcool
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-audit/", views.nova_avaliacao_audit, name="nova_avaliacao_audit"),
    path("audit/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.audit_form,           name="audit_form"),
    path("audit/<uuid:avaliacao_id>/resultado/",               views.audit_resultado,      name="audit_resultado"),
    path("audit/<uuid:avaliacao_id>/deletar/",                 views.audit_deletar,        name="audit_deletar"),
    path("audit/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_audit, name="salvar_observacoes_audit"),
    path("audit/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.audit_visualizar,     name="audit_visualizar"),
    path("audit/publico/<str:token>/<int:pagina>/",            views.audit_publico,        name="audit_publico"),
    path("audit/<uuid:avaliacao_id>/email/",                   views.enviar_email_audit,   name="enviar_email_audit"),
    path("audit/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "audit"}, name="audit_laudo"),
    # BIS-11 — Impulsividade de Barratt
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bis11/", views.nova_avaliacao_bis11, name="nova_avaliacao_bis11"),
    path("bis11/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.bis11_form,           name="bis11_form"),
    path("bis11/<uuid:avaliacao_id>/resultado/",               views.bis11_resultado,      name="bis11_resultado"),
    path("bis11/<uuid:avaliacao_id>/deletar/",                 views.bis11_deletar,        name="bis11_deletar"),
    path("bis11/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_bis11, name="salvar_observacoes_bis11"),
    path("bis11/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.bis11_visualizar,     name="bis11_visualizar"),
    path("bis11/publico/<str:token>/<int:pagina>/",            views.bis11_publico,        name="bis11_publico"),
    path("bis11/<uuid:avaliacao_id>/email/",                   views.enviar_email_bis11,   name="enviar_email_bis11"),
    path("bis11/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "bis11"}, name="bis11_laudo"),
    # IAR — Ansiedade Infantil
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-iar/", views.nova_avaliacao_iar, name="nova_avaliacao_iar"),
    path("iar/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.iar_form,           name="iar_form"),
    path("iar/<uuid:avaliacao_id>/resultado/",               views.iar_resultado,      name="iar_resultado"),
    path("iar/<uuid:avaliacao_id>/deletar/",                 views.iar_deletar,        name="iar_deletar"),
    path("iar/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_iar, name="salvar_observacoes_iar"),
    path("iar/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.iar_visualizar,     name="iar_visualizar"),
    path("iar/publico/<str:token>/<int:pagina>/",            views.iar_publico,        name="iar_publico"),
    path("iar/<uuid:avaliacao_id>/email/",                   views.enviar_email_iar,   name="enviar_email_iar"),
    path("iar/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "iar"}, name="iar_laudo"),
    # PAS — Ansiedade Pré-Escolar
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-pas/", views.nova_avaliacao_pas, name="nova_avaliacao_pas"),
    path("pas/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.pas_form,           name="pas_form"),
    path("pas/<uuid:avaliacao_id>/resultado/",               views.pas_resultado,      name="pas_resultado"),
    path("pas/<uuid:avaliacao_id>/deletar/",                 views.pas_deletar,        name="pas_deletar"),
    path("pas/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_pas, name="salvar_observacoes_pas"),
    path("pas/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.pas_visualizar,     name="pas_visualizar"),
    path("pas/publico/<str:token>/<int:pagina>/",            views.pas_publico,        name="pas_publico"),
    path("pas/<uuid:avaliacao_id>/email/",                   views.enviar_email_pas,   name="enviar_email_pas"),
    path("pas/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "pas"}, name="pas_laudo"),
    # CDI — Depressão Infantil
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-cdi/", views.nova_avaliacao_cdi, name="nova_avaliacao_cdi"),
    path("cdi/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.cdi_form,           name="cdi_form"),
    path("cdi/<uuid:avaliacao_id>/resultado/",               views.cdi_resultado,      name="cdi_resultado"),
    path("cdi/<uuid:avaliacao_id>/deletar/",                 views.cdi_deletar,        name="cdi_deletar"),
    path("cdi/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_cdi, name="salvar_observacoes_cdi"),
    path("cdi/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.cdi_visualizar,     name="cdi_visualizar"),
    path("cdi/publico/<str:token>/<int:pagina>/",            views.cdi_publico,        name="cdi_publico"),
    path("cdi/<uuid:avaliacao_id>/email/",                   views.enviar_email_cdi,   name="enviar_email_cdi"),
    path("cdi/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "cdi"}, name="cdi_laudo"),
    # HAM-A — Ansiedade de Hamilton
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-hama/", views.nova_avaliacao_hama, name="nova_avaliacao_hama"),
    path("hama/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.hama_form,           name="hama_form"),
    path("hama/<uuid:avaliacao_id>/resultado/",               views.hama_resultado,      name="hama_resultado"),
    path("hama/<uuid:avaliacao_id>/deletar/",                 views.hama_deletar,        name="hama_deletar"),
    path("hama/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_hama, name="salvar_observacoes_hama"),
    path("hama/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.hama_visualizar,     name="hama_visualizar"),
    path("hama/publico/<str:token>/<int:pagina>/",            views.hama_publico,        name="hama_publico"),
    path("hama/<uuid:avaliacao_id>/email/",                   views.enviar_email_hama,   name="enviar_email_hama"),
    path("hama/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "hama"}, name="hama_laudo"),
    # LSAS — Ansiedade Social de Liebowitz
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-lsas/", views.nova_avaliacao_lsas, name="nova_avaliacao_lsas"),
    path("lsas/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.lsas_form,           name="lsas_form"),
    path("lsas/<uuid:avaliacao_id>/resultado/",               views.lsas_resultado,      name="lsas_resultado"),
    path("lsas/<uuid:avaliacao_id>/deletar/",                 views.lsas_deletar,        name="lsas_deletar"),
    path("lsas/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_lsas, name="salvar_observacoes_lsas"),
    path("lsas/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.lsas_visualizar,     name="lsas_visualizar"),
    path("lsas/publico/<str:token>/<int:pagina>/",            views.lsas_publico,        name="lsas_publico"),
    path("lsas/<uuid:avaliacao_id>/email/",                   views.enviar_email_lsas,   name="enviar_email_lsas"),
    path("lsas/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "lsas"}, name="lsas_laudo"),
    # Triagem de Risco de Suicídio
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-risco-suicidio/", views.nova_avaliacao_risco_suicidio, name="nova_avaliacao_risco_suicidio"),
    path("risco-suicidio/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.risco_suicidio_form,           name="risco_suicidio_form"),
    path("risco-suicidio/<uuid:avaliacao_id>/resultado/",               views.risco_suicidio_resultado,      name="risco_suicidio_resultado"),
    path("risco-suicidio/<uuid:avaliacao_id>/deletar/",                 views.risco_suicidio_deletar,        name="risco_suicidio_deletar"),
    path("risco-suicidio/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_risco_suicidio, name="salvar_observacoes_risco_suicidio"),
    path("risco-suicidio/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.risco_suicidio_visualizar,     name="risco_suicidio_visualizar"),
    path("risco-suicidio/publico/<str:token>/<int:pagina>/",            views.risco_suicidio_publico,        name="risco_suicidio_publico"),
    path("risco-suicidio/<uuid:avaliacao_id>/email/",                   views.enviar_email_risco_suicidio,   name="enviar_email_risco_suicidio"),
    path("risco-suicidio/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "risco_suicidio"}, name="risco_suicidio_laudo"),
    # Rastreio de Agorafobia
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-agorafobia/", views.nova_avaliacao_agorafobia, name="nova_avaliacao_agorafobia"),
    path("agorafobia/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.agorafobia_form,           name="agorafobia_form"),
    path("agorafobia/<uuid:avaliacao_id>/resultado/",               views.agorafobia_resultado,      name="agorafobia_resultado"),
    path("agorafobia/<uuid:avaliacao_id>/deletar/",                 views.agorafobia_deletar,        name="agorafobia_deletar"),
    path("agorafobia/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_agorafobia, name="salvar_observacoes_agorafobia"),
    path("agorafobia/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.agorafobia_visualizar,     name="agorafobia_visualizar"),
    path("agorafobia/publico/<str:token>/<int:pagina>/",            views.agorafobia_publico,        name="agorafobia_publico"),
    path("agorafobia/<uuid:avaliacao_id>/email/",                   views.enviar_email_agorafobia,   name="enviar_email_agorafobia"),
    path("agorafobia/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "agorafobia"}, name="agorafobia_laudo"),
    # Rastreio de Pânico
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-panico/", views.nova_avaliacao_panico, name="nova_avaliacao_panico"),
    path("panico/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.panico_form,           name="panico_form"),
    path("panico/<uuid:avaliacao_id>/resultado/",               views.panico_resultado,      name="panico_resultado"),
    path("panico/<uuid:avaliacao_id>/deletar/",                 views.panico_deletar,        name="panico_deletar"),
    path("panico/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_panico, name="salvar_observacoes_panico"),
    path("panico/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.panico_visualizar,     name="panico_visualizar"),
    path("panico/publico/<str:token>/<int:pagina>/",            views.panico_publico,        name="panico_publico"),
    path("panico/<uuid:avaliacao_id>/email/",                   views.enviar_email_panico,   name="enviar_email_panico"),
    path("panico/<uuid:avaliacao_id>/laudo/", views.laudo_generico, {"tipo": "panico"}, name="panico_laudo"),
    # PHQ-9
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-phq9/",      views.nova_avaliacao_phq9,       name="nova_avaliacao_phq9"),
    path("phq9/<uuid:avaliacao_id>/pagina/<int:pagina>/",           views.phq9_form,                 name="phq9_form"),
    path("phq9/<uuid:avaliacao_id>/resultado/",                     views.phq9_resultado,            name="phq9_resultado"),
    path("phq9/<uuid:avaliacao_id>/deletar/",                       views.phq9_deletar,              name="phq9_deletar"),
    path("phq9/<uuid:avaliacao_id>/observacoes/",                   views.salvar_observacoes_phq9,   name="salvar_observacoes_phq9"),
    path("phq9/<uuid:avaliacao_id>/visualizar/<int:pagina>/",       views.phq9_visualizar,           name="phq9_visualizar"),
    path("phq9/publico/<str:token>/<int:pagina>/",                  views.phq9_publico,              name="phq9_publico"),
    path("phq9/<uuid:avaliacao_id>/email/",                         views.enviar_email_phq9,         name="enviar_email_phq9"),
    # GAD-7
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-gad7/",      views.nova_avaliacao_gad7,       name="nova_avaliacao_gad7"),
    path("gad7/<uuid:avaliacao_id>/pagina/<int:pagina>/",           views.gad7_form,                 name="gad7_form"),
    path("gad7/<uuid:avaliacao_id>/resultado/",                     views.gad7_resultado,            name="gad7_resultado"),
    path("gad7/<uuid:avaliacao_id>/deletar/",                       views.gad7_deletar,              name="gad7_deletar"),
    path("gad7/<uuid:avaliacao_id>/observacoes/",                   views.salvar_observacoes_gad7,   name="salvar_observacoes_gad7"),
    path("gad7/<uuid:avaliacao_id>/visualizar/<int:pagina>/",       views.gad7_visualizar,           name="gad7_visualizar"),
    path("gad7/publico/<str:token>/<int:pagina>/",                  views.gad7_publico,              name="gad7_publico"),
    path("gad7/<uuid:avaliacao_id>/email/",                         views.enviar_email_gad7,         name="enviar_email_gad7"),
    # EPDS
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-epds/",      views.nova_avaliacao_epds,       name="nova_avaliacao_epds"),
    path("epds/<uuid:avaliacao_id>/pagina/<int:pagina>/",           views.epds_form,                 name="epds_form"),
    path("epds/<uuid:avaliacao_id>/resultado/",                     views.epds_resultado,            name="epds_resultado"),
    path("epds/<uuid:avaliacao_id>/deletar/",                       views.epds_deletar,              name="epds_deletar"),
    path("epds/<uuid:avaliacao_id>/observacoes/",                   views.salvar_observacoes_epds,   name="salvar_observacoes_epds"),
    path("epds/<uuid:avaliacao_id>/visualizar/<int:pagina>/",       views.epds_visualizar,           name="epds_visualizar"),
    path("epds/publico/<str:token>/<int:pagina>/",                  views.epds_publico,              name="epds_publico"),
    path("epds/<uuid:avaliacao_id>/email/",                         views.enviar_email_epds,         name="enviar_email_epds"),
    # PCL-5
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-pcl5/",      views.nova_avaliacao_pcl5,       name="nova_avaliacao_pcl5"),
    path("pcl5/<uuid:avaliacao_id>/pagina/<int:pagina>/",           views.pcl5_form,                 name="pcl5_form"),
    path("pcl5/<uuid:avaliacao_id>/resultado/",                     views.pcl5_resultado,            name="pcl5_resultado"),
    path("pcl5/<uuid:avaliacao_id>/deletar/",                       views.pcl5_deletar,              name="pcl5_deletar"),
    path("pcl5/<uuid:avaliacao_id>/observacoes/",                   views.salvar_observacoes_pcl5,   name="salvar_observacoes_pcl5"),
    path("pcl5/<uuid:avaliacao_id>/visualizar/<int:pagina>/",       views.pcl5_visualizar,           name="pcl5_visualizar"),
    path("pcl5/publico/<str:token>/<int:pagina>/",                  views.pcl5_publico,              name="pcl5_publico"),
    path("pcl5/<uuid:avaliacao_id>/email/",                         views.enviar_email_pcl5,         name="enviar_email_pcl5"),
    # GHQ-12
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-ghq12/",     views.nova_avaliacao_ghq12,      name="nova_avaliacao_ghq12"),
    path("ghq12/<uuid:avaliacao_id>/pagina/<int:pagina>/",          views.ghq12_form,                name="ghq12_form"),
    path("ghq12/<uuid:avaliacao_id>/resultado/",                    views.ghq12_resultado,           name="ghq12_resultado"),
    path("ghq12/<uuid:avaliacao_id>/deletar/",                      views.ghq12_deletar,             name="ghq12_deletar"),
    path("ghq12/<uuid:avaliacao_id>/observacoes/",                  views.salvar_observacoes_ghq12,  name="salvar_observacoes_ghq12"),
    path("ghq12/<uuid:avaliacao_id>/visualizar/<int:pagina>/",      views.ghq12_visualizar,          name="ghq12_visualizar"),
    path("ghq12/publico/<str:token>/<int:pagina>/",                 views.ghq12_publico,             name="ghq12_publico"),
    path("ghq12/<uuid:avaliacao_id>/email/",                        views.enviar_email_ghq12,        name="enviar_email_ghq12"),
    # BAI — Inventário de Ansiedade de Beck
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bai/",       views.nova_avaliacao_bai,           name="nova_avaliacao_bai"),
    path("bai/<uuid:avaliacao_id>/pagina/<int:pagina>/",            views.bai_form,                     name="bai_form"),
    path("bai/<uuid:avaliacao_id>/resultado/",                      views.bai_resultado,                name="bai_resultado"),
    path("bai/<uuid:avaliacao_id>/deletar/",                        views.bai_deletar,                  name="bai_deletar"),
    path("bai/<uuid:avaliacao_id>/observacoes/",                    views.salvar_observacoes_bai,       name="salvar_observacoes_bai"),
    path("bai/<uuid:avaliacao_id>/visualizar/<int:pagina>/",        views.bai_visualizar,               name="bai_visualizar"),
    path("bai/publico/<str:token>/<int:pagina>/",                   views.bai_publico,                  name="bai_publico"),
    path("bai/<uuid:avaliacao_id>/email/",                          views.enviar_email_bai,             name="enviar_email_bai"),
    # DASS-21
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-dass21/",    views.nova_avaliacao_dass21,        name="nova_avaliacao_dass21"),
    path("dass21/<uuid:avaliacao_id>/pagina/<int:pagina>/",         views.dass21_form,                  name="dass21_form"),
    path("dass21/<uuid:avaliacao_id>/resultado/",                   views.dass21_resultado,             name="dass21_resultado"),
    path("dass21/<uuid:avaliacao_id>/deletar/",                     views.dass21_deletar,               name="dass21_deletar"),
    path("dass21/<uuid:avaliacao_id>/observacoes/",                 views.salvar_observacoes_dass21,    name="salvar_observacoes_dass21"),
    path("dass21/<uuid:avaliacao_id>/visualizar/<int:pagina>/",     views.dass21_visualizar,            name="dass21_visualizar"),
    path("dass21/publico/<str:token>/<int:pagina>/",                views.dass21_publico,               name="dass21_publico"),
    path("dass21/<uuid:avaliacao_id>/email/",                       views.enviar_email_dass21,          name="enviar_email_dass21"),
    # HAD — Escala de Ansiedade e Depressão Hospitalar
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-had/",       views.nova_avaliacao_had,           name="nova_avaliacao_had"),
    path("had/<uuid:avaliacao_id>/pagina/<int:pagina>/",            views.had_form,                     name="had_form"),
    path("had/<uuid:avaliacao_id>/resultado/",                      views.had_resultado,                name="had_resultado"),
    path("had/<uuid:avaliacao_id>/deletar/",                        views.had_deletar,                  name="had_deletar"),
    path("had/<uuid:avaliacao_id>/observacoes/",                    views.salvar_observacoes_had,       name="salvar_observacoes_had"),
    path("had/<uuid:avaliacao_id>/visualizar/<int:pagina>/",        views.had_visualizar,               name="had_visualizar"),
    path("had/publico/<str:token>/<int:pagina>/",                   views.had_publico,                  name="had_publico"),
    path("had/<uuid:avaliacao_id>/email/",                          views.enviar_email_had,             name="enviar_email_had"),
    # BSL-23 — Sintomas Borderline
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bsl23/",     views.nova_avaliacao_bsl23,         name="nova_avaliacao_bsl23"),
    path("bsl23/<uuid:avaliacao_id>/pagina/<int:pagina>/",          views.bsl23_form,                   name="bsl23_form"),
    path("bsl23/<uuid:avaliacao_id>/resultado/",                    views.bsl23_resultado,              name="bsl23_resultado"),
    path("bsl23/<uuid:avaliacao_id>/deletar/",                      views.bsl23_deletar,                name="bsl23_deletar"),
    path("bsl23/<uuid:avaliacao_id>/observacoes/",                  views.salvar_observacoes_bsl23,     name="salvar_observacoes_bsl23"),
    path("bsl23/<uuid:avaliacao_id>/visualizar/<int:pagina>/",      views.bsl23_visualizar,             name="bsl23_visualizar"),
    path("bsl23/publico/<str:token>/<int:pagina>/",                 views.bsl23_publico,                name="bsl23_publico"),
    path("bsl23/<uuid:avaliacao_id>/email/",                        views.enviar_email_bsl23,           name="enviar_email_bsl23"),
    # AQ-10 Adulto
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-aq10-adulto/", views.nova_avaliacao_aq10_adulto, name="nova_avaliacao_aq10_adulto"),
    path("aq10-adulto/<uuid:avaliacao_id>/pagina/<int:pagina>/",    views.aq10_adulto_form,             name="aq10_adulto_form"),
    path("aq10-adulto/<uuid:avaliacao_id>/resultado/",              views.aq10_adulto_resultado,        name="aq10_adulto_resultado"),
    path("aq10-adulto/<uuid:avaliacao_id>/deletar/",                views.aq10_adulto_deletar,          name="aq10_adulto_deletar"),
    path("aq10-adulto/<uuid:avaliacao_id>/observacoes/",            views.salvar_observacoes_aq10_adulto, name="salvar_observacoes_aq10_adulto"),
    path("aq10-adulto/<uuid:avaliacao_id>/visualizar/<int:pagina>/",views.aq10_adulto_visualizar,       name="aq10_adulto_visualizar"),
    path("aq10-adulto/publico/<str:token>/<int:pagina>/",           views.aq10_adulto_publico,          name="aq10_adulto_publico"),
    path("aq10-adulto/<uuid:avaliacao_id>/email/",                  views.enviar_email_aq10_adulto,     name="enviar_email_aq10_adulto"),
    # AQ-10 Criança
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-aq10-child/", views.nova_avaliacao_aq10_child,   name="nova_avaliacao_aq10_child"),
    path("aq10-child/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.aq10_child_form,              name="aq10_child_form"),
    path("aq10-child/<uuid:avaliacao_id>/resultado/",               views.aq10_child_resultado,         name="aq10_child_resultado"),
    path("aq10-child/<uuid:avaliacao_id>/deletar/",                 views.aq10_child_deletar,           name="aq10_child_deletar"),
    path("aq10-child/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_aq10_child, name="salvar_observacoes_aq10_child"),
    path("aq10-child/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.aq10_child_visualizar,        name="aq10_child_visualizar"),
    path("aq10-child/publico/<str:token>/<int:pagina>/",            views.aq10_child_publico,           name="aq10_child_publico"),
    path("aq10-child/<uuid:avaliacao_id>/email/",                   views.enviar_email_aq10_child,      name="enviar_email_aq10_child"),
    # Dependência Emocional
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-dep-emocional/", views.nova_avaliacao_dep_emocional, name="nova_avaliacao_dep_emocional"),
    path("dep-emocional/<uuid:avaliacao_id>/pagina/<int:pagina>/",  views.dep_emocional_form,           name="dep_emocional_form"),
    path("dep-emocional/<uuid:avaliacao_id>/resultado/",            views.dep_emocional_resultado,      name="dep_emocional_resultado"),
    path("dep-emocional/<uuid:avaliacao_id>/deletar/",              views.dep_emocional_deletar,        name="dep_emocional_deletar"),
    path("dep-emocional/<uuid:avaliacao_id>/observacoes/",          views.salvar_observacoes_dep_emocional, name="salvar_observacoes_dep_emocional"),
    path("dep-emocional/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.dep_emocional_visualizar,  name="dep_emocional_visualizar"),
    path("dep-emocional/publico/<str:token>/<int:pagina>/",         views.dep_emocional_publico,        name="dep_emocional_publico"),
    path("dep-emocional/<uuid:avaliacao_id>/email/",                views.enviar_email_dep_emocional,   name="enviar_email_dep_emocional"),
    # SCQ — Comunicação Social
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-scq/",       views.nova_avaliacao_scq,           name="nova_avaliacao_scq"),
    path("scq/<uuid:avaliacao_id>/pagina/<int:pagina>/",            views.scq_form,                     name="scq_form"),
    path("scq/<uuid:avaliacao_id>/resultado/",                      views.scq_resultado,                name="scq_resultado"),
    path("scq/<uuid:avaliacao_id>/deletar/",                        views.scq_deletar,                  name="scq_deletar"),
    path("scq/<uuid:avaliacao_id>/observacoes/",                    views.salvar_observacoes_scq,       name="salvar_observacoes_scq"),
    path("scq/<uuid:avaliacao_id>/visualizar/<int:pagina>/",        views.scq_visualizar,               name="scq_visualizar"),
    path("scq/publico/<str:token>/<int:pagina>/",                   views.scq_publico,                  name="scq_publico"),
    path("scq/<uuid:avaliacao_id>/email/",                          views.enviar_email_scq,             name="enviar_email_scq"),
    # ── Conners-3 Pais ────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-conners-pais/",  views.nova_avaliacao_conners_pais,        name="nova_avaliacao_conners_pais"),
    path("conners-pais/<uuid:avaliacao_id>/pagina/<int:pagina>/",      views.conners_pais_form,                  name="conners_pais_form"),
    path("conners-pais/<uuid:avaliacao_id>/resultado/",                views.conners_pais_resultado,             name="conners_pais_resultado"),
    path("conners-pais/<uuid:avaliacao_id>/visualizar/<int:pagina>/",  views.conners_pais_visualizar,            name="conners_pais_visualizar"),
    path("conners-pais/<uuid:avaliacao_id>/deletar/",                  views.conners_pais_deletar,               name="conners_pais_deletar"),
    path("conners-pais/<uuid:avaliacao_id>/observacoes/",              views.salvar_observacoes_conners_pais,    name="salvar_observacoes_conners_pais"),
    path("conners-pais/<uuid:avaliacao_id>/enviar-link/",              views.enviar_email_conners_pais,          name="enviar_email_conners_pais"),
    path("conners-pais/publico/<str:token>/<int:pagina>/",             views.conners_pais_publico,               name="conners_pais_publico"),
    # ── Conners-3 Professor ───────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-conners-prof/",  views.nova_avaliacao_conners_prof,        name="nova_avaliacao_conners_prof"),
    path("conners-prof/<uuid:avaliacao_id>/pagina/<int:pagina>/",      views.conners_prof_form,                  name="conners_prof_form"),
    path("conners-prof/<uuid:avaliacao_id>/resultado/",                views.conners_prof_resultado,             name="conners_prof_resultado"),
    path("conners-prof/<uuid:avaliacao_id>/visualizar/<int:pagina>/",  views.conners_prof_visualizar,            name="conners_prof_visualizar"),
    path("conners-prof/<uuid:avaliacao_id>/deletar/",                  views.conners_prof_deletar,               name="conners_prof_deletar"),
    path("conners-prof/<uuid:avaliacao_id>/observacoes/",              views.salvar_observacoes_conners_prof,    name="salvar_observacoes_conners_prof"),
    path("conners-prof/<uuid:avaliacao_id>/enviar-link/",              views.enviar_email_conners_prof,          name="enviar_email_conners_prof"),
    path("conners-prof/publico/<str:token>/<int:pagina>/",             views.conners_prof_publico,               name="conners_prof_publico"),
    # ── ETDAH Pais ───────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-etdah-pais/",    views.nova_avaliacao_etdah_pais,          name="nova_avaliacao_etdah_pais"),
    path("etdah-pais/<uuid:avaliacao_id>/pagina/<int:pagina>/",        views.etdah_pais_form,                    name="etdah_pais_form"),
    path("etdah-pais/<uuid:avaliacao_id>/resultado/",                  views.etdah_pais_resultado,               name="etdah_pais_resultado"),
    path("etdah-pais/<uuid:avaliacao_id>/visualizar/<int:pagina>/",    views.etdah_pais_visualizar,              name="etdah_pais_visualizar"),
    path("etdah-pais/<uuid:avaliacao_id>/deletar/",                    views.etdah_pais_deletar,                 name="etdah_pais_deletar"),
    path("etdah-pais/<uuid:avaliacao_id>/observacoes/",                views.salvar_observacoes_etdah_pais,      name="salvar_observacoes_etdah_pais"),
    path("etdah-pais/<uuid:avaliacao_id>/enviar-link/",                views.enviar_email_etdah_pais,            name="enviar_email_etdah_pais"),
    path("etdah-pais/publico/<str:token>/<int:pagina>/",               views.etdah_pais_publico,                 name="etdah_pais_publico"),
    # ── ETDAH Professor ───────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-etdah-prof/",    views.nova_avaliacao_etdah_prof,          name="nova_avaliacao_etdah_prof"),
    path("etdah-prof/<uuid:avaliacao_id>/pagina/<int:pagina>/",        views.etdah_prof_form,                    name="etdah_prof_form"),
    path("etdah-prof/<uuid:avaliacao_id>/resultado/",                  views.etdah_prof_resultado,               name="etdah_prof_resultado"),
    path("etdah-prof/<uuid:avaliacao_id>/visualizar/<int:pagina>/",    views.etdah_prof_visualizar,              name="etdah_prof_visualizar"),
    path("etdah-prof/<uuid:avaliacao_id>/deletar/",                    views.etdah_prof_deletar,                 name="etdah_prof_deletar"),
    path("etdah-prof/<uuid:avaliacao_id>/observacoes/",                views.salvar_observacoes_etdah_prof,      name="salvar_observacoes_etdah_prof"),
    path("etdah-prof/<uuid:avaliacao_id>/enviar-link/",                views.enviar_email_etdah_prof,            name="enviar_email_etdah_prof"),
    path("etdah-prof/publico/<str:token>/<int:pagina>/",               views.etdah_prof_publico,                 name="etdah_prof_publico"),
    # ── AUQEI ─────────────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-auqei/",         views.nova_avaliacao_auqei,               name="nova_avaliacao_auqei"),
    path("auqei/<uuid:avaliacao_id>/pagina/<int:pagina>/",             views.auqei_form,                         name="auqei_form"),
    path("auqei/<uuid:avaliacao_id>/resultado/",                       views.auqei_resultado,                    name="auqei_resultado"),
    path("auqei/<uuid:avaliacao_id>/visualizar/<int:pagina>/",         views.auqei_visualizar,                   name="auqei_visualizar"),
    path("auqei/<uuid:avaliacao_id>/deletar/",                         views.auqei_deletar,                      name="auqei_deletar"),
    path("auqei/<uuid:avaliacao_id>/observacoes/",                     views.salvar_observacoes_auqei,           name="salvar_observacoes_auqei"),
    path("auqei/<uuid:avaliacao_id>/enviar-link/",                     views.enviar_email_auqei,                 name="enviar_email_auqei"),
    path("auqei/publico/<str:token>/<int:pagina>/",                    views.auqei_publico,                      name="auqei_publico"),
    # ── SCARED ────────────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-scared/",        views.nova_avaliacao_scared,              name="nova_avaliacao_scared"),
    path("scared/<uuid:avaliacao_id>/pagina/<int:pagina>/",            views.scared_form,                        name="scared_form"),
    path("scared/<uuid:avaliacao_id>/resultado/",                      views.scared_resultado,                   name="scared_resultado"),
    path("scared/<uuid:avaliacao_id>/visualizar/<int:pagina>/",        views.scared_visualizar,                  name="scared_visualizar"),
    path("scared/<uuid:avaliacao_id>/deletar/",                        views.scared_deletar,                     name="scared_deletar"),
    path("scared/<uuid:avaliacao_id>/observacoes/",                    views.salvar_observacoes_scared,          name="salvar_observacoes_scared"),
    path("scared/<uuid:avaliacao_id>/enviar-link/",                    views.enviar_email_scared,                name="enviar_email_scared"),
    path("scared/publico/<str:token>/<int:pagina>/",                   views.scared_publico,                     name="scared_publico"),
    # ── MASC ──────────────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-masc/",          views.nova_avaliacao_masc,                name="nova_avaliacao_masc"),
    path("masc/<uuid:avaliacao_id>/pagina/<int:pagina>/",              views.masc_form,                          name="masc_form"),
    path("masc/<uuid:avaliacao_id>/resultado/",                        views.masc_resultado,                     name="masc_resultado"),
    path("masc/<uuid:avaliacao_id>/visualizar/<int:pagina>/",          views.masc_visualizar,                    name="masc_visualizar"),
    path("masc/<uuid:avaliacao_id>/deletar/",                          views.masc_deletar,                       name="masc_deletar"),
    path("masc/<uuid:avaliacao_id>/observacoes/",                      views.salvar_observacoes_masc,            name="salvar_observacoes_masc"),
    path("masc/<uuid:avaliacao_id>/enviar-link/",                      views.enviar_email_masc,                  name="enviar_email_masc"),
    path("masc/publico/<str:token>/<int:pagina>/",                     views.masc_publico,                       name="masc_publico"),
    # ── BPQ ───────────────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bpq/",           views.nova_avaliacao_bpq,                 name="nova_avaliacao_bpq"),
    path("bpq/<uuid:avaliacao_id>/pagina/<int:pagina>/",               views.bpq_form,                           name="bpq_form"),
    path("bpq/<uuid:avaliacao_id>/resultado/",                         views.bpq_resultado,                      name="bpq_resultado"),
    path("bpq/<uuid:avaliacao_id>/visualizar/<int:pagina>/",           views.bpq_visualizar,                     name="bpq_visualizar"),
    path("bpq/<uuid:avaliacao_id>/deletar/",                           views.bpq_deletar,                        name="bpq_deletar"),
    path("bpq/<uuid:avaliacao_id>/observacoes/",                       views.salvar_observacoes_bpq,             name="salvar_observacoes_bpq"),
    path("bpq/<uuid:avaliacao_id>/enviar-link/",                       views.enviar_email_bpq,                   name="enviar_email_bpq"),
    path("bpq/publico/<str:token>/<int:pagina>/",                      views.bpq_publico,                        name="bpq_publico"),
    # ── Denver II ────────────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-denver/",         views.nova_avaliacao_denver,              name="nova_avaliacao_denver"),
    path("denver/<uuid:avaliacao_id>/pagina/<int:pagina>/",             views.denver_form,                        name="denver_form"),
    path("denver/<uuid:avaliacao_id>/resultado/",                       views.denver_resultado,                   name="denver_resultado"),
    path("denver/<uuid:avaliacao_id>/deletar/",                         views.denver_deletar,                     name="denver_deletar"),
    path("denver/<uuid:avaliacao_id>/observacoes/",                     views.salvar_observacoes_denver,          name="salvar_observacoes_denver"),
    path("denver/<uuid:avaliacao_id>/visualizar/<int:pagina>/",         views.denver_visualizar,                  name="denver_visualizar"),
    path("denver/publico/<str:token>/<int:pagina>/",                    views.denver_publico,                     name="denver_publico"),
    path("denver/<uuid:avaliacao_id>/enviar-email/",                    views.enviar_email_denver,                name="enviar_email_denver"),
    # ── QMPI ─────────────────────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-qmpi/",           views.nova_avaliacao_qmpi,                name="nova_avaliacao_qmpi"),
    path("qmpi/<uuid:avaliacao_id>/pagina/<int:pagina>/",               views.qmpi_form,                          name="qmpi_form"),
    path("qmpi/<uuid:avaliacao_id>/resultado/",                         views.qmpi_resultado,                     name="qmpi_resultado"),
    path("qmpi/<uuid:avaliacao_id>/deletar/",                           views.qmpi_deletar,                       name="qmpi_deletar"),
    path("qmpi/<uuid:avaliacao_id>/observacoes/",                       views.salvar_observacoes_qmpi,            name="salvar_observacoes_qmpi"),
    path("qmpi/<uuid:avaliacao_id>/visualizar/<int:pagina>/",           views.qmpi_visualizar,                    name="qmpi_visualizar"),
    path("qmpi/<uuid:avaliacao_id>/email/",                             views.enviar_email_qmpi,                  name="enviar_email_qmpi"),
    path("qmpi/publico/<str:token>/<int:pagina>/",                      views.qmpi_publico,                       name="qmpi_publico"),
    # ── Questionário de Dislexia (Pais) ──────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-quest-dislexia/", views.nova_avaliacao_quest_dislexia,      name="nova_avaliacao_quest_dislexia"),
    path("quest-dislexia/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.quest_dislexia_form,                name="quest_dislexia_form"),
    path("quest-dislexia/<uuid:avaliacao_id>/resultado/",               views.quest_dislexia_resultado,           name="quest_dislexia_resultado"),
    path("quest-dislexia/<uuid:avaliacao_id>/deletar/",                 views.quest_dislexia_deletar,             name="quest_dislexia_deletar"),
    path("quest-dislexia/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_quest_dislexia,  name="salvar_observacoes_quest_dislexia"),
    path("quest-dislexia/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.quest_dislexia_visualizar,          name="quest_dislexia_visualizar"),
    path("quest-dislexia/<uuid:avaliacao_id>/email/",                   views.enviar_email_quest_dislexia,        name="enviar_email_quest_dislexia"),
    path("quest-dislexia/publico/<str:token>/<int:pagina>/",            views.quest_dislexia_publico,             name="quest_dislexia_publico"),
    # ── Checklist de Dislexia ─────────────────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-checklist-dislexia/", views.nova_avaliacao_checklist_dislexia,   name="nova_avaliacao_checklist_dislexia"),
    path("checklist-dislexia/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.checklist_dislexia_form,             name="checklist_dislexia_form"),
    path("checklist-dislexia/<uuid:avaliacao_id>/resultado/",               views.checklist_dislexia_resultado,        name="checklist_dislexia_resultado"),
    path("checklist-dislexia/<uuid:avaliacao_id>/deletar/",                 views.checklist_dislexia_deletar,          name="checklist_dislexia_deletar"),
    path("checklist-dislexia/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_checklist_dislexia, name="salvar_observacoes_checklist_dislexia"),
    path("checklist-dislexia/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.checklist_dislexia_visualizar,       name="checklist_dislexia_visualizar"),
    path("checklist-dislexia/<uuid:avaliacao_id>/email/",                   views.enviar_email_checklist_dislexia,     name="enviar_email_checklist_dislexia"),
    path("checklist-dislexia/publico/<str:token>/<int:pagina>/",            views.checklist_dislexia_publico,          name="checklist_dislexia_publico"),
    # ── Protocolo Dislexia — Professor ───────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-prot-dislexia-prof/", views.nova_avaliacao_prot_dislexia_prof,   name="nova_avaliacao_prot_dislexia_prof"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/pagina/<int:pagina>/",     views.prot_dislexia_prof_form,             name="prot_dislexia_prof_form"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/resultado/",               views.prot_dislexia_prof_resultado,        name="prot_dislexia_prof_resultado"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/deletar/",                 views.prot_dislexia_prof_deletar,          name="prot_dislexia_prof_deletar"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/observacoes/",             views.salvar_observacoes_prot_dislexia_prof, name="salvar_observacoes_prot_dislexia_prof"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/visualizar/<int:pagina>/", views.prot_dislexia_prof_visualizar,       name="prot_dislexia_prof_visualizar"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/email/",                   views.enviar_email_prot_dislexia_prof,     name="enviar_email_prot_dislexia_prof"),
    path("prot-dislexia-prof/publico/<str:token>/<int:pagina>/",            views.prot_dislexia_prof_publico,          name="prot_dislexia_prof_publico"),
    # ── Inventário de Sinais Disléxicos ───────────────────────────────────────────
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-inventario-dislexia/", views.nova_avaliacao_inventario_dislexia, name="nova_avaliacao_inventario_dislexia"),
    path("inventario-dislexia/<uuid:avaliacao_id>/form/",                    views.inventario_dislexia_form,           name="inventario_dislexia_form"),
    path("inventario-dislexia/<uuid:avaliacao_id>/resultado/",               views.inventario_dislexia_resultado,      name="inventario_dislexia_resultado"),
    path("inventario-dislexia/<uuid:avaliacao_id>/deletar/",                 views.inventario_dislexia_deletar,        name="inventario_dislexia_deletar"),
    # ── Laudos genéricos (todos os instrumentos) ──────────────────────────────
    path("spm/<uuid:avaliacao_id>/laudo/",                       views.laudo_generico, {"tipo": "spm"},             name="spm_laudo"),
    path("vineland/<uuid:avaliacao_id>/laudo/",                  views.laudo_generico, {"tipo": "vineland"},        name="vineland_laudo"),
    path("escolar/<uuid:avaliacao_id>/laudo/",                   views.laudo_generico, {"tipo": "escolar"},         name="escolar_laudo"),
    path("bebe/<uuid:avaliacao_id>/laudo/",                      views.laudo_generico, {"tipo": "bebe"},            name="bebe_laudo"),
    path("edm/<uuid:avaliacao_id>/laudo/",                       views.laudo_generico, {"tipo": "edm"},             name="edm_laudo"),
    path("mabc2/<uuid:avaliacao_id>/laudo/",                     views.laudo_generico, {"tipo": "mabc2"},           name="mabc2_laudo"),
    path("beery/<uuid:avaliacao_id>/laudo/",                     views.laudo_generico, {"tipo": "beery"},           name="beery_laudo"),
    path("pedi/<uuid:avaliacao_id>/laudo/",                      views.laudo_generico, {"tipo": "pedi"},            name="pedi_laudo"),
    path("vineland3/<uuid:avaliacao_id>/laudo/",                 views.laudo_generico, {"tipo": "vineland3"},       name="vineland3_laudo"),
    path("portage/<uuid:avaliacao_id>/laudo/",                   views.laudo_generico, {"tipo": "portage"},         name="portage_laudo"),
    path("sdq/<uuid:avaliacao_id>/laudo/",                       views.laudo_generico, {"tipo": "sdq"},             name="sdq_laudo"),
    path("snap-iv/<uuid:avaliacao_id>/laudo/",                   views.laudo_generico, {"tipo": "snap_iv"},         name="snap_iv_laudo"),
    path("mchat/<uuid:avaliacao_id>/laudo/",                     views.laudo_generico, {"tipo": "mchat"},           name="mchat_laudo"),
    path("cars/<uuid:avaliacao_id>/laudo/",                      views.laudo_generico, {"tipo": "cars"},            name="cars_laudo"),
    path("linguagem/<uuid:avaliacao_id>/laudo/",                 views.laudo_generico, {"tipo": "linguagem"},       name="linguagem_laudo"),
    path("alimentacao/<uuid:avaliacao_id>/laudo/",               views.laudo_generico, {"tipo": "alimentacao"},     name="alimentacao_laudo"),
    path("habitos-orais/<uuid:avaliacao_id>/laudo/",             views.laudo_generico, {"tipo": "habitos"},         name="habitos_laudo"),
    path("voz-infantil/<uuid:avaliacao_id>/laudo/",              views.laudo_generico, {"tipo": "voz"},             name="voz_laudo"),
    path("processamento-auditivo/<uuid:avaliacao_id>/laudo/",    views.laudo_generico, {"tipo": "auditivo"},        name="auditivo_laudo"),
    path("idv10/<uuid:avaliacao_id>/laudo/",                     views.laudo_generico, {"tipo": "idv"},             name="idv_laudo"),
    path("desenvolvimento/<uuid:avaliacao_id>/laudo/",           views.laudo_generico, {"tipo": "desenvolvimento"}, name="desenvolvimento_laudo"),
    path("sono/<uuid:avaliacao_id>/laudo/",                      views.laudo_generico, {"tipo": "sono"},            name="sono_laudo"),
    path("habilidades/<uuid:avaliacao_id>/laudo/",               views.laudo_generico, {"tipo": "habilidades"},     name="habilidades_laudo"),
    path("comportamento/<uuid:avaliacao_id>/laudo/",             views.laudo_generico, {"tipo": "comportamento"},   name="comportamento_laudo"),
    path("cognitivo/<uuid:avaliacao_id>/laudo/",                 views.laudo_generico, {"tipo": "cognitivo"},       name="cognitivo_laudo"),
    path("psicopedagogica/<uuid:avaliacao_id>/laudo/",           views.laudo_generico, {"tipo": "psicopedagogica"}, name="psicopedagogica_laudo"),
    # ── Laudos Lote 2 — Psicologia ──────────────────────────────────────────────
    path("bdi/<uuid:avaliacao_id>/laudo/",              views.laudo_generico, {"tipo": "bdi"},              name="bdi_laudo"),
    path("bai/<uuid:avaliacao_id>/laudo/",              views.laudo_generico, {"tipo": "bai"},              name="bai_laudo"),
    path("dass21/<uuid:avaliacao_id>/laudo/",           views.laudo_generico, {"tipo": "dass21"},           name="dass21_laudo"),
    path("had/<uuid:avaliacao_id>/laudo/",              views.laudo_generico, {"tipo": "had"},              name="had_laudo"),
    path("bsl23/<uuid:avaliacao_id>/laudo/",            views.laudo_generico, {"tipo": "bsl23"},            name="bsl23_laudo"),
    path("aq10-adulto/<uuid:avaliacao_id>/laudo/",      views.laudo_generico, {"tipo": "aq10_adulto"},      name="aq10_adulto_laudo"),
    path("aq10-child/<uuid:avaliacao_id>/laudo/",       views.laudo_generico, {"tipo": "aq10_child"},       name="aq10_child_laudo"),
    path("scq/<uuid:avaliacao_id>/laudo/",              views.laudo_generico, {"tipo": "scq"},              name="scq_laudo"),
    path("dep-emocional/<uuid:avaliacao_id>/laudo/",    views.laudo_generico, {"tipo": "dep_emocional"},    name="dep_emocional_laudo"),
    path("conners-pais/<uuid:avaliacao_id>/laudo/",     views.laudo_generico, {"tipo": "conners_pais"},     name="conners_pais_laudo"),
    path("conners-prof/<uuid:avaliacao_id>/laudo/",     views.laudo_generico, {"tipo": "conners_prof"},     name="conners_prof_laudo"),
    path("etdah-pais/<uuid:avaliacao_id>/laudo/",       views.laudo_generico, {"tipo": "etdah_pais"},       name="etdah_pais_laudo"),
    path("etdah-prof/<uuid:avaliacao_id>/laudo/",       views.laudo_generico, {"tipo": "etdah_prof"},       name="etdah_prof_laudo"),
    path("auqei/<uuid:avaliacao_id>/laudo/",            views.laudo_generico, {"tipo": "auqei"},            name="auqei_laudo"),
    path("scared/<uuid:avaliacao_id>/laudo/",           views.laudo_generico, {"tipo": "scared"},           name="scared_laudo"),
    path("masc/<uuid:avaliacao_id>/laudo/",             views.laudo_generico, {"tipo": "masc"},             name="masc_laudo"),
    path("bpq/<uuid:avaliacao_id>/laudo/",              views.laudo_generico, {"tipo": "bpq"},              name="bpq_laudo"),
    # ── Laudos Lote 3 ───────────────────────────────────────────────────────────
    path("qmpi/<uuid:avaliacao_id>/laudo/",                  views.laudo_generico, {"tipo": "qmpi"},              name="qmpi_laudo"),
    path("denver/<uuid:avaliacao_id>/laudo/",                views.laudo_generico, {"tipo": "denver"},            name="denver_laudo"),
    path("quest-dislexia/<uuid:avaliacao_id>/laudo/",        views.laudo_generico, {"tipo": "quest_dislexia"},    name="quest_dislexia_laudo"),
    path("checklist-dislexia/<uuid:avaliacao_id>/laudo/",    views.laudo_generico, {"tipo": "checklist_dislexia"},name="checklist_dislexia_laudo"),
    path("prot-dislexia-prof/<uuid:avaliacao_id>/laudo/",    views.laudo_generico, {"tipo": "prot_dislexia_prof"},name="prot_dislexia_prof_laudo"),
    path("phq9/<uuid:avaliacao_id>/laudo/",   views.laudo_generico, {"tipo": "phq9"},  name="phq9_laudo"),
    path("gad7/<uuid:avaliacao_id>/laudo/",   views.laudo_generico, {"tipo": "gad7"},  name="gad7_laudo"),
    path("epds/<uuid:avaliacao_id>/laudo/",   views.laudo_generico, {"tipo": "epds"},  name="epds_laudo"),
    path("pcl5/<uuid:avaliacao_id>/laudo/",   views.laudo_generico, {"tipo": "pcl5"},  name="pcl5_laudo"),
    path("ghq12/<uuid:avaliacao_id>/laudo/",  views.laudo_generico, {"tipo": "ghq12"}, name="ghq12_laudo"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__404__/", lambda r: render(r, "erros/404.html", status=404)),
        path("__403__/", lambda r: render(r, "403.html", status=403)),
        path("__500__/", lambda r: render(r, "500.html", status=500)),
    ]
