from django.urls import path
from . import views

urlpatterns = [
    # Link de Convite (gerado pelo médico, preenchido pelo paciente)
    path("gerar-link/", views.gerar_link, name="gerar_link"),
    path("gerar-link/enviar-email/", views.enviar_email_convite, name="enviar_email_convite"),
    path("iniciar/<uuid:token>/", views.iniciar_avaliacao, name="iniciar_avaliacao"),
    # Auth
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("registrar/", views.registrar_view, name="registrar"),
    path("meu-perfil/", views.meu_perfil, name="meu_perfil"),
    # App
    path("", views.index, name="index"),
    path("pacientes/", views.lista_pacientes, name="lista_pacientes"),
    path("pacientes/novo/", views.novo_paciente, name="novo_paciente"),
    path("pacientes/<uuid:paciente_id>/", views.detalhe_paciente, name="detalhe_paciente"),
    path("pacientes/<uuid:paciente_id>/nova-avaliacao/", views.nova_avaliacao, name="nova_avaliacao"),
    path("avaliacao/<int:avaliacao_id>/pagina/<int:pagina>/", views.questionario_view, name="questionario"),
    path("questionario/publico/<str:token>/<int:pagina>/", views.questionario_publico_view, name="questionario_publico"),
    path("avaliacao/<int:avaliacao_id>/concluir/", views.concluir, name="concluir"),
    path("avaliacao/<int:avaliacao_id>/dashboard/", views.dashboard, name="dashboard"),
    path("avaliacao/<int:avaliacao_id>/deletar/", views.deletar_avaliacao, name="deletar_avaliacao"),
    path("avaliacao/<int:avaliacao_id>/enviar-link/", views.enviar_email_link, name="enviar_email_link"),
    path("avaliacao/<int:avaliacao_id>/observacoes/", views.salvar_observacoes, name="salvar_observacoes"),
    path("pacientes/<uuid:paciente_id>/editar/", views.editar_paciente, name="editar_paciente"),
    path("pacientes/<uuid:paciente_id>/deletar/", views.deletar_paciente, name="deletar_paciente"),
    # Vineland
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-vineland/", views.nova_avaliacao_vineland, name="nova_avaliacao_vineland"),
    path("vineland/<int:avaliacao_id>/pagina/<int:pagina>/", views.vineland_form, name="vineland_form"),
    path("vineland/<int:avaliacao_id>/concluir/", views.vineland_concluir, name="vineland_concluir"),
    path("vineland/<int:avaliacao_id>/resultado/", views.vineland_resultado, name="vineland_resultado"),
    path("vineland/<int:avaliacao_id>/deletar/", views.vineland_deletar, name="vineland_deletar"),
    path("vineland/publico/<str:token>/<int:pagina>/", views.vineland_publico_view, name="vineland_publico"),
    path("vineland/<int:avaliacao_id>/enviar-link/", views.enviar_email_link_vineland, name="enviar_email_link_vineland"),
    path("vineland/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_vineland, name="salvar_observacoes_vineland"),
    # Questionário Sensorial Escolar
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-escolar/", views.nova_avaliacao_escolar, name="nova_avaliacao_escolar"),
    path("escolar/<int:avaliacao_id>/pagina/<int:pagina>/", views.escolar_form, name="escolar_form"),
    path("escolar/<int:avaliacao_id>/concluir/", views.escolar_concluir, name="escolar_concluir"),
    path("escolar/<int:avaliacao_id>/resultado/", views.escolar_resultado, name="escolar_resultado"),
    path("escolar/<int:avaliacao_id>/deletar/", views.escolar_deletar, name="escolar_deletar"),
    path("escolar/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_escolar, name="salvar_observacoes_escolar"),
    path("escolar/publico/<str:token>/<int:pagina>/", views.escolar_publico_view, name="escolar_publico"),
    path("escolar/<int:avaliacao_id>/enviar-link/", views.enviar_email_escolar, name="enviar_email_escolar"),
    # Perfil Sensorial Bebê/Criança Pequena
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bebe/", views.nova_avaliacao_bebe, name="nova_avaliacao_bebe"),
    path("bebe/<int:avaliacao_id>/pagina/<int:pagina>/", views.bebe_form, name="bebe_form"),
    path("bebe/<int:avaliacao_id>/concluir/", views.bebe_concluir, name="bebe_concluir"),
    path("bebe/<int:avaliacao_id>/resultado/", views.bebe_resultado, name="bebe_resultado"),
    path("bebe/<int:avaliacao_id>/deletar/", views.bebe_deletar, name="bebe_deletar"),
    path("bebe/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_bebe, name="salvar_observacoes_bebe"),
    path("bebe/publico/<str:token>/<int:pagina>/", views.bebe_publico_view, name="bebe_publico"),
    path("bebe/<int:avaliacao_id>/enviar-link/", views.enviar_email_bebe, name="enviar_email_bebe"),
    # SPM — Sensory Processing Measure
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-spm/", views.nova_avaliacao_spm, name="nova_avaliacao_spm"),
    path("spm/<int:avaliacao_id>/pagina/<int:pagina>/", views.spm_form, name="spm_form"),
    path("spm/<int:avaliacao_id>/concluir/", views.spm_concluir, name="spm_concluir"),
    path("spm/<int:avaliacao_id>/resultado/", views.spm_resultado, name="spm_resultado"),
    path("spm/<int:avaliacao_id>/deletar/", views.spm_deletar, name="spm_deletar"),
    path("spm/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_spm, name="salvar_observacoes_spm"),
    path("spm/publico/<str:token>/<int:pagina>/", views.spm_publico_view, name="spm_publico"),
    path("spm/<int:avaliacao_id>/enviar-link/", views.enviar_email_spm, name="enviar_email_spm"),
    # EDM
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-edm/", views.nova_avaliacao_edm, name="nova_avaliacao_edm"),
    path("edm/<int:avaliacao_id>/", views.edm_form, name="edm_form"),
    path("edm/<int:avaliacao_id>/resultado/", views.edm_resultado, name="edm_resultado"),
    path("edm/<int:avaliacao_id>/deletar/", views.edm_deletar, name="edm_deletar"),
    path("edm/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_edm, name="salvar_observacoes_edm"),
    # MABC-2
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-mabc2/", views.nova_avaliacao_mabc2, name="nova_avaliacao_mabc2"),
    path("mabc2/<int:avaliacao_id>/", views.mabc2_form, name="mabc2_form"),
    path("mabc2/<int:avaliacao_id>/resultado/", views.mabc2_resultado, name="mabc2_resultado"),
    path("mabc2/<int:avaliacao_id>/deletar/", views.mabc2_deletar, name="mabc2_deletar"),
    path("mabc2/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_mabc2, name="salvar_observacoes_mabc2"),
    # Beery VMI
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-beery/", views.nova_avaliacao_beery, name="nova_avaliacao_beery"),
    path("beery/<int:avaliacao_id>/", views.beery_form, name="beery_form"),
    path("beery/<int:avaliacao_id>/resultado/", views.beery_resultado, name="beery_resultado"),
    path("beery/<int:avaliacao_id>/deletar/", views.beery_deletar, name="beery_deletar"),
    path("beery/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_beery, name="salvar_observacoes_beery"),
    # PEDI
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-pedi/", views.nova_avaliacao_pedi, name="nova_avaliacao_pedi"),
    path("pedi/<int:avaliacao_id>/", views.pedi_form, name="pedi_form"),
    path("pedi/<int:avaliacao_id>/resultado/", views.pedi_resultado, name="pedi_resultado"),
    path("pedi/<int:avaliacao_id>/deletar/", views.pedi_deletar, name="pedi_deletar"),
    path("pedi/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_pedi, name="salvar_observacoes_pedi"),
]
