from django.conf import settings
from django.shortcuts import render
from django.urls import path
from . import views

urlpatterns = [
    # Link de Convite (gerado pelo médico, preenchido pelo paciente)
    path("gerar-link/", views.gerar_link, name="gerar_link"),
    path("gerar-link/enviar-email/", views.enviar_email_convite, name="enviar_email_convite"),
    path("iniciar/<uuid:token>/", views.iniciar_avaliacao, name="iniciar_avaliacao"),
    # Auth
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("registrar/", views.registrar_view, name="registrar"),
    path("confirmar-email/<uidb64>/<token>/", views.confirmar_email_view, name="confirmar_email"),
    path("meu-perfil/", views.meu_perfil, name="meu_perfil"),
    path("privacidade/", views.politica_privacidade, name="politica_privacidade"),
    path("trial-expirado/", views.trial_expirado, name="trial_expirado"),
    # App
    path("", views.index, name="index"),
    path("pacientes/", views.lista_pacientes, name="lista_pacientes"),
    path("pacientes/novo/", views.novo_paciente, name="novo_paciente"),
    path("pacientes/<uuid:paciente_id>/", views.detalhe_paciente, name="detalhe_paciente"),
    path("pacientes/<uuid:paciente_id>/nova-avaliacao/", views.nova_avaliacao, name="nova_avaliacao"),
    path("avaliacao/<int:avaliacao_id>/pagina/<int:pagina>/", views.questionario_view, name="questionario"),
    path("questionario/publico/<str:token>/<int:pagina>/", views.questionario_publico_view, name="questionario_publico"),
    path("avaliacao/<int:avaliacao_id>/concluir/", views.concluir, name="concluir"),
    path("avaliacao/<int:avaliacao_id>/dashboard/", views.dashboard, name="dashboard"),
    path("avaliacao/<int:avaliacao_id>/visualizar/<int:pagina>/", views.questionario_visualizar, name="questionario_visualizar"),
    path("avaliacao/<int:avaliacao_id>/deletar/", views.deletar_avaliacao, name="deletar_avaliacao"),
    path("avaliacao/<int:avaliacao_id>/enviar-link/", views.enviar_email_link, name="enviar_email_link"),
    path("avaliacao/<int:avaliacao_id>/observacoes/", views.salvar_observacoes, name="salvar_observacoes"),
    path("pacientes/<uuid:paciente_id>/editar/", views.editar_paciente, name="editar_paciente"),
    path("pacientes/<uuid:paciente_id>/deletar/", views.deletar_paciente, name="deletar_paciente"),
    # Vineland
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-vineland/", views.nova_avaliacao_vineland, name="nova_avaliacao_vineland"),
    path("vineland/<int:avaliacao_id>/pagina/<int:pagina>/", views.vineland_form, name="vineland_form"),
    path("vineland/<int:avaliacao_id>/concluir/", views.vineland_concluir, name="vineland_concluir"),
    path("vineland/<int:avaliacao_id>/resultado/", views.vineland_resultado, name="vineland_resultado"),
    path("vineland/<int:avaliacao_id>/visualizar/<int:pagina>/", views.vineland_visualizar, name="vineland_visualizar"),
    path("vineland/<int:avaliacao_id>/deletar/", views.vineland_deletar, name="vineland_deletar"),
    path("vineland/publico/<str:token>/<int:pagina>/", views.vineland_publico_view, name="vineland_publico"),
    path("vineland/<int:avaliacao_id>/enviar-link/", views.enviar_email_link_vineland, name="enviar_email_link_vineland"),
    path("vineland/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_vineland, name="salvar_observacoes_vineland"),
    # Questionário Sensorial Escolar
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-escolar/", views.nova_avaliacao_escolar, name="nova_avaliacao_escolar"),
    path("escolar/<int:avaliacao_id>/pagina/<int:pagina>/", views.escolar_form, name="escolar_form"),
    path("escolar/<int:avaliacao_id>/concluir/", views.escolar_concluir, name="escolar_concluir"),
    path("escolar/<int:avaliacao_id>/resultado/", views.escolar_resultado, name="escolar_resultado"),
    path("escolar/<int:avaliacao_id>/visualizar/<int:pagina>/", views.escolar_visualizar, name="escolar_visualizar"),
    path("escolar/<int:avaliacao_id>/deletar/", views.escolar_deletar, name="escolar_deletar"),
    path("escolar/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_escolar, name="salvar_observacoes_escolar"),
    path("escolar/publico/<str:token>/<int:pagina>/", views.escolar_publico_view, name="escolar_publico"),
    path("escolar/<int:avaliacao_id>/enviar-link/", views.enviar_email_escolar, name="enviar_email_escolar"),
    # Perfil Sensorial Bebê/Criança Pequena
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-bebe/", views.nova_avaliacao_bebe, name="nova_avaliacao_bebe"),
    path("bebe/<int:avaliacao_id>/pagina/<int:pagina>/", views.bebe_form, name="bebe_form"),
    path("bebe/<int:avaliacao_id>/concluir/", views.bebe_concluir, name="bebe_concluir"),
    path("bebe/<int:avaliacao_id>/resultado/", views.bebe_resultado, name="bebe_resultado"),
    path("bebe/<int:avaliacao_id>/visualizar/<int:pagina>/", views.bebe_visualizar, name="bebe_visualizar"),
    path("bebe/<int:avaliacao_id>/deletar/", views.bebe_deletar, name="bebe_deletar"),
    path("bebe/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_bebe, name="salvar_observacoes_bebe"),
    path("bebe/publico/<str:token>/<int:pagina>/", views.bebe_publico_view, name="bebe_publico"),
    path("bebe/<int:avaliacao_id>/enviar-link/", views.enviar_email_bebe, name="enviar_email_bebe"),
    # SPM — Sensory Processing Measure
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-spm/", views.nova_avaliacao_spm, name="nova_avaliacao_spm"),
    path("spm/<int:avaliacao_id>/pagina/<int:pagina>/", views.spm_form, name="spm_form"),
    path("spm/<int:avaliacao_id>/concluir/", views.spm_concluir, name="spm_concluir"),
    path("spm/<int:avaliacao_id>/resultado/", views.spm_resultado, name="spm_resultado"),
    path("spm/<int:avaliacao_id>/visualizar/<int:pagina>/", views.spm_visualizar, name="spm_visualizar"),
    path("spm/<int:avaliacao_id>/deletar/", views.spm_deletar, name="spm_deletar"),
    path("spm/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_spm, name="salvar_observacoes_spm"),
    path("spm/publico/<str:token>/<int:pagina>/", views.spm_publico_view, name="spm_publico"),
    path("spm/<int:avaliacao_id>/enviar-link/", views.enviar_email_spm, name="enviar_email_spm"),
    # EDM
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-edm/", views.nova_avaliacao_edm, name="nova_avaliacao_edm"),
    path("edm/<int:avaliacao_id>/", views.edm_form, name="edm_form"),
    path("edm/<int:avaliacao_id>/resultado/", views.edm_resultado, name="edm_resultado"),
    path("edm/<int:avaliacao_id>/deletar/", views.edm_deletar, name="edm_deletar"),
    path("edm/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_edm, name="salvar_observacoes_edm"),
    # MABC-2
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-mabc2/", views.nova_avaliacao_mabc2, name="nova_avaliacao_mabc2"),
    path("mabc2/<int:avaliacao_id>/", views.mabc2_form, name="mabc2_form"),
    path("mabc2/<int:avaliacao_id>/resultado/", views.mabc2_resultado, name="mabc2_resultado"),
    path("mabc2/<int:avaliacao_id>/deletar/", views.mabc2_deletar, name="mabc2_deletar"),
    path("mabc2/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_mabc2, name="salvar_observacoes_mabc2"),
    # Beery VMI
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-beery/", views.nova_avaliacao_beery, name="nova_avaliacao_beery"),
    path("beery/<int:avaliacao_id>/", views.beery_form, name="beery_form"),
    path("beery/<int:avaliacao_id>/resultado/", views.beery_resultado, name="beery_resultado"),
    path("beery/<int:avaliacao_id>/deletar/", views.beery_deletar, name="beery_deletar"),
    path("beery/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_beery, name="salvar_observacoes_beery"),
    # PEDI
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-pedi/", views.nova_avaliacao_pedi, name="nova_avaliacao_pedi"),
    path("pedi/<int:avaliacao_id>/", views.pedi_form, name="pedi_form"),
    path("pedi/<int:avaliacao_id>/resultado/", views.pedi_resultado, name="pedi_resultado"),
    path("pedi/<int:avaliacao_id>/deletar/", views.pedi_deletar, name="pedi_deletar"),
    path("pedi/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_pedi, name="salvar_observacoes_pedi"),
    path("pedi/<int:avaliacao_id>/enviar-email/", views.enviar_email_pedi, name="enviar_email_pedi"),
    path("pedi/<int:avaliacao_id>/visualizar/", views.pedi_visualizar, name="pedi_visualizar"),
    path("pedi/<int:avaliacao_id>/salvar-progresso/", views.pedi_salvar_progresso, name="pedi_salvar_progresso"),
    path("pedi/publico/<str:token>/salvar-progresso/", views.pedi_salvar_progresso_publico, name="pedi_salvar_progresso_publico"),
    path("pedi/publico/<str:token>/<int:pagina>/", views.pedi_publico, name="pedi_publico"),
    path("pedi/publico/<str:token>/", views.pedi_publico_redirect, name="pedi_publico_sem_pagina"),
    # Vineland-3
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-vineland3/", views.nova_avaliacao_vineland3, name="nova_avaliacao_vineland3"),
    path("vineland3/<int:avaliacao_id>/pagina/<int:pagina>/", views.vineland3_form, name="vineland3_form"),
    path("vineland3/<int:avaliacao_id>/concluir/", views.vineland3_concluir, name="vineland3_concluir"),
    path("vineland3/<int:avaliacao_id>/resultado/", views.vineland3_resultado, name="vineland3_resultado"),
    path("vineland3/<int:avaliacao_id>/visualizar/<int:pagina>/", views.vineland3_visualizar, name="vineland3_visualizar"),
    path("vineland3/<int:avaliacao_id>/deletar/", views.vineland3_deletar, name="vineland3_deletar"),
    path("vineland3/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_vineland3, name="salvar_observacoes_vineland3"),
    path("vineland3/<int:avaliacao_id>/enviar-link/", views.enviar_email_vineland3, name="enviar_email_vineland3"),
    path("vineland3/publico/<str:token>/<int:pagina>/", views.vineland3_publico_view, name="vineland3_publico"),
    # Guia Portage
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-portage/", views.nova_avaliacao_portage, name="nova_avaliacao_portage"),
    path("portage/<int:avaliacao_id>/pagina/<int:pagina>/", views.portage_form, name="portage_form"),
    path("portage/<int:avaliacao_id>/concluir/", views.portage_concluir, name="portage_concluir"),
    path("portage/<int:avaliacao_id>/resultado/", views.portage_resultado, name="portage_resultado"),
    path("portage/<int:avaliacao_id>/deletar/", views.portage_deletar, name="portage_deletar"),
    path("portage/<int:avaliacao_id>/visualizar/<int:pagina>/", views.portage_visualizar, name="portage_visualizar"),
    path("portage/publico/<str:token>/<int:pagina>/", views.portage_publico_view, name="portage_publico"),
    # SDQ
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-sdq/", views.nova_avaliacao_sdq, name="nova_avaliacao_sdq"),
    path("sdq/<int:avaliacao_id>/pagina/<int:pagina>/", views.sdq_form, name="sdq_form"),
    path("sdq/<int:avaliacao_id>/resultado/", views.sdq_resultado, name="sdq_resultado"),
    path("sdq/<int:avaliacao_id>/deletar/", views.sdq_deletar, name="sdq_deletar"),
    path("sdq/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_sdq, name="salvar_observacoes_sdq"),
    path("sdq/<int:avaliacao_id>/enviar-link/", views.enviar_email_sdq, name="enviar_email_sdq"),
    path("sdq/<int:avaliacao_id>/visualizar/<int:pagina>/", views.sdq_visualizar, name="sdq_visualizar"),
    path("sdq/publico/<str:token>/<int:pagina>/", views.sdq_publico, name="sdq_publico"),
    # SNAP-IV
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-snap-iv/", views.nova_avaliacao_snap_iv, name="nova_avaliacao_snap_iv"),
    path("snap-iv/<int:avaliacao_id>/pagina/<int:pagina>/", views.snap_iv_form, name="snap_iv_form"),
    path("snap-iv/<int:avaliacao_id>/resultado/", views.snap_iv_resultado, name="snap_iv_resultado"),
    path("snap-iv/<int:avaliacao_id>/deletar/", views.snap_iv_deletar, name="snap_iv_deletar"),
    path("snap-iv/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_snap_iv, name="salvar_observacoes_snap_iv"),
    path("snap-iv/<int:avaliacao_id>/enviar-link/", views.enviar_email_snap_iv, name="enviar_email_snap_iv"),
    path("snap-iv/<int:avaliacao_id>/visualizar/<int:pagina>/", views.snap_iv_visualizar, name="snap_iv_visualizar"),
    path("snap-iv/publico/<str:token>/<int:pagina>/", views.snap_iv_publico, name="snap_iv_publico"),
    # M-CHAT-R
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-mchat/", views.nova_avaliacao_mchat, name="nova_avaliacao_mchat"),
    path("mchat/<int:avaliacao_id>/", views.mchat_form, name="mchat_form"),
    path("mchat/<int:avaliacao_id>/resultado/", views.mchat_resultado, name="mchat_resultado"),
    path("mchat/<int:avaliacao_id>/deletar/", views.mchat_deletar, name="mchat_deletar"),
    path("mchat/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_mchat, name="salvar_observacoes_mchat"),
    path("mchat/<int:avaliacao_id>/enviar-link/", views.enviar_email_mchat, name="enviar_email_mchat"),
    path("mchat/<int:avaliacao_id>/visualizar/", views.mchat_visualizar, name="mchat_visualizar"),
    path("mchat/publico/<str:token>/", views.mchat_publico, name="mchat_publico"),
    # E-mail genérico para novos módulos multiprofissionais
    path("modulo/<str:modulo>/<int:avaliacao_id>/enviar-email/", views.enviar_email_modulo, name="enviar_email_modulo"),
    # CARS-2
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-cars/", views.nova_avaliacao_cars, name="nova_avaliacao_cars"),
    path("cars/<int:avaliacao_id>/", views.cars_form, name="cars_form"),
    path("cars/<int:avaliacao_id>/resultado/", views.cars_resultado, name="cars_resultado"),
    path("cars/<int:avaliacao_id>/deletar/", views.cars_deletar, name="cars_deletar"),
    path("cars/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_cars, name="salvar_observacoes_cars"),
    path("cars/<int:avaliacao_id>/enviar-link/", views.enviar_email_cars, name="enviar_email_cars"),
    path("cars/<int:avaliacao_id>/visualizar/", views.cars_visualizar, name="cars_visualizar"),
    path("cars/publico/<str:token>/", views.cars_publico, name="cars_publico"),
    # Avaliação de Linguagem
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-linguagem/", views.nova_avaliacao_linguagem, name="nova_avaliacao_linguagem"),
    path("linguagem/<int:avaliacao_id>/pagina/<int:pagina>/", views.linguagem_form, name="linguagem_form"),
    path("linguagem/<int:avaliacao_id>/resultado/", views.linguagem_resultado, name="linguagem_resultado"),
    path("linguagem/<int:avaliacao_id>/deletar/", views.linguagem_deletar, name="linguagem_deletar"),
    path("linguagem/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_linguagem, name="salvar_observacoes_linguagem"),
    path("linguagem/<int:avaliacao_id>/visualizar/<int:pagina>/", views.linguagem_visualizar, name="linguagem_visualizar"),
    path("linguagem/publico/<str:token>/<int:pagina>/", views.linguagem_publico, name="linguagem_publico"),
    # Triagem de Alimentação
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-alimentacao/", views.nova_avaliacao_alimentacao, name="nova_avaliacao_alimentacao"),
    path("alimentacao/<int:avaliacao_id>/pagina/<int:pagina>/", views.alimentacao_form, name="alimentacao_form"),
    path("alimentacao/<int:avaliacao_id>/resultado/", views.alimentacao_resultado, name="alimentacao_resultado"),
    path("alimentacao/<int:avaliacao_id>/deletar/", views.alimentacao_deletar, name="alimentacao_deletar"),
    path("alimentacao/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_alimentacao, name="salvar_observacoes_alimentacao"),
    path("alimentacao/<int:avaliacao_id>/visualizar/<int:pagina>/", views.alimentacao_visualizar, name="alimentacao_visualizar"),
    path("alimentacao/publico/<str:token>/<int:pagina>/", views.alimentacao_publico, name="alimentacao_publico"),
    # Hábitos Orais
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-habitos-orais/", views.nova_avaliacao_habitos_orais, name="nova_avaliacao_habitos_orais"),
    path("habitos-orais/<int:avaliacao_id>/pagina/<int:pagina>/", views.habitos_orais_form, name="habitos_form"),
    path("habitos-orais/<int:avaliacao_id>/resultado/", views.habitos_orais_resultado, name="habitos_resultado"),
    path("habitos-orais/<int:avaliacao_id>/deletar/", views.habitos_orais_deletar, name="habitos_deletar"),
    path("habitos-orais/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_habitos_orais, name="salvar_observacoes_habitos_orais"),
    path("habitos-orais/<int:avaliacao_id>/visualizar/<int:pagina>/", views.habitos_orais_visualizar, name="habitos_visualizar"),
    path("habitos-orais/publico/<str:token>/<int:pagina>/", views.habitos_orais_publico, name="habitos_publico"),
    # Voz Infantil
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-voz-infantil/", views.nova_avaliacao_voz_infantil, name="nova_avaliacao_voz_infantil"),
    path("voz-infantil/<int:avaliacao_id>/pagina/<int:pagina>/", views.voz_infantil_form, name="voz_form"),
    path("voz-infantil/<int:avaliacao_id>/resultado/", views.voz_infantil_resultado, name="voz_resultado"),
    path("voz-infantil/<int:avaliacao_id>/deletar/", views.voz_infantil_deletar, name="voz_deletar"),
    path("voz-infantil/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_voz_infantil, name="salvar_observacoes_voz_infantil"),
    path("voz-infantil/<int:avaliacao_id>/visualizar/<int:pagina>/", views.voz_infantil_visualizar, name="voz_visualizar"),
    path("voz-infantil/publico/<str:token>/<int:pagina>/", views.voz_infantil_publico, name="voz_publico"),
    # Processamento Auditivo
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-auditivo/", views.nova_avaliacao_processamento_auditivo, name="nova_avaliacao_processamento_auditivo"),
    path("processamento-auditivo/<int:avaliacao_id>/pagina/<int:pagina>/", views.processamento_auditivo_form, name="auditivo_form"),
    path("processamento-auditivo/<int:avaliacao_id>/resultado/", views.processamento_auditivo_resultado, name="auditivo_resultado"),
    path("processamento-auditivo/<int:avaliacao_id>/deletar/", views.processamento_auditivo_deletar, name="auditivo_deletar"),
    path("processamento-auditivo/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_processamento_auditivo, name="salvar_observacoes_processamento_auditivo"),
    path("processamento-auditivo/<int:avaliacao_id>/visualizar/<int:pagina>/", views.processamento_auditivo_visualizar, name="auditivo_visualizar"),
    path("processamento-auditivo/publico/<str:token>/<int:pagina>/", views.processamento_auditivo_publico, name="auditivo_publico"),
    # IDV-10
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-idv10/", views.nova_avaliacao_idv10, name="nova_avaliacao_idv10"),
    path("idv10/<int:avaliacao_id>/pagina/<int:pagina>/", views.idv10_form, name="idv_form"),
    path("idv10/<int:avaliacao_id>/resultado/", views.idv10_resultado, name="idv_resultado"),
    path("idv10/<int:avaliacao_id>/deletar/", views.idv10_deletar, name="idv_deletar"),
    path("idv10/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_idv10, name="salvar_observacoes_idv10"),
    path("idv10/<int:avaliacao_id>/visualizar/<int:pagina>/", views.idv10_visualizar, name="idv_visualizar"),
    path("idv10/publico/<str:token>/<int:pagina>/", views.idv10_publico, name="idv_publico"),
    # Marcos de Desenvolvimento
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-desenvolvimento/", views.nova_avaliacao_desenvolvimento, name="nova_avaliacao_desenvolvimento"),
    path("desenvolvimento/<int:avaliacao_id>/pagina/<int:pagina>/", views.desenvolvimento_form, name="desenvolvimento_form"),
    path("desenvolvimento/<int:avaliacao_id>/resultado/", views.desenvolvimento_resultado, name="desenvolvimento_resultado"),
    path("desenvolvimento/<int:avaliacao_id>/deletar/", views.desenvolvimento_deletar, name="desenvolvimento_deletar"),
    path("desenvolvimento/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_desenvolvimento, name="salvar_observacoes_desenvolvimento"),
    path("desenvolvimento/<int:avaliacao_id>/visualizar/<int:pagina>/", views.desenvolvimento_visualizar, name="desenvolvimento_visualizar"),
    path("desenvolvimento/publico/<str:token>/<int:pagina>/", views.desenvolvimento_publico, name="desenvolvimento_publico"),
    # Avaliação de Sono Infantil
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-sono/", views.nova_avaliacao_sono, name="nova_avaliacao_sono"),
    path("sono/<int:avaliacao_id>/pagina/<int:pagina>/", views.sono_form, name="sono_form"),
    path("sono/<int:avaliacao_id>/resultado/", views.sono_resultado, name="sono_resultado"),
    path("sono/<int:avaliacao_id>/deletar/", views.sono_deletar, name="sono_deletar"),
    path("sono/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_sono, name="salvar_observacoes_sono"),
    path("sono/<int:avaliacao_id>/visualizar/<int:pagina>/", views.sono_visualizar, name="sono_visualizar"),
    path("sono/publico/<str:token>/<int:pagina>/", views.sono_publico, name="sono_publico"),
    # Habilidades Adaptativas
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-habilidades/", views.nova_avaliacao_habilidades_adaptativas, name="nova_avaliacao_habilidades"),
    path("habilidades/<int:avaliacao_id>/pagina/<int:pagina>/", views.habilidades_adaptativas_form, name="habilidades_form"),
    path("habilidades/<int:avaliacao_id>/resultado/", views.habilidades_adaptativas_resultado, name="habilidades_resultado"),
    path("habilidades/<int:avaliacao_id>/deletar/", views.habilidades_adaptativas_deletar, name="habilidades_deletar"),
    path("habilidades/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_habilidades_adaptativas, name="salvar_observacoes_habilidades"),
    path("habilidades/<int:avaliacao_id>/visualizar/<int:pagina>/", views.habilidades_adaptativas_visualizar, name="habilidades_visualizar"),
    path("habilidades/publico/<str:token>/<int:pagina>/", views.habilidades_adaptativas_publico, name="habilidades_publico"),
    # Comportamento Funcional
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-comportamento/", views.nova_avaliacao_comportamento_funcional, name="nova_avaliacao_comportamento"),
    path("comportamento/<int:avaliacao_id>/pagina/<int:pagina>/", views.comportamento_funcional_form, name="comportamento_form"),
    path("comportamento/<int:avaliacao_id>/resultado/", views.comportamento_funcional_resultado, name="comportamento_resultado"),
    path("comportamento/<int:avaliacao_id>/deletar/", views.comportamento_funcional_deletar, name="comportamento_deletar"),
    path("comportamento/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_comportamento_funcional, name="salvar_observacoes_comportamento"),
    path("comportamento/<int:avaliacao_id>/visualizar/<int:pagina>/", views.comportamento_funcional_visualizar, name="comportamento_visualizar"),
    path("comportamento/publico/<str:token>/<int:pagina>/", views.comportamento_funcional_publico, name="comportamento_publico"),
    # Rastreio Cognitivo
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-cognitivo/", views.nova_avaliacao_cognitivo, name="nova_avaliacao_cognitivo"),
    path("cognitivo/<int:avaliacao_id>/pagina/<int:pagina>/", views.cognitivo_form, name="cognitivo_form"),
    path("cognitivo/<int:avaliacao_id>/resultado/", views.cognitivo_resultado, name="cognitivo_resultado"),
    path("cognitivo/<int:avaliacao_id>/deletar/", views.cognitivo_deletar, name="cognitivo_deletar"),
    path("cognitivo/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_cognitivo, name="salvar_observacoes_cognitivo"),
    path("cognitivo/<int:avaliacao_id>/visualizar/<int:pagina>/", views.cognitivo_visualizar, name="cognitivo_visualizar"),
    path("cognitivo/publico/<str:token>/<int:pagina>/", views.cognitivo_publico, name="cognitivo_publico"),
    # Avaliação Psicopedagógica
    path("pacientes/<uuid:paciente_id>/nova-avaliacao-psicopedagogica/", views.nova_avaliacao_psicopedagogica, name="nova_avaliacao_psicopedagogica"),
    path("psicopedagogica/<int:avaliacao_id>/pagina/<int:pagina>/", views.psicopedagogica_form, name="psicopedagogica_form"),
    path("psicopedagogica/<int:avaliacao_id>/resultado/", views.psicopedagogica_resultado, name="psicopedagogica_resultado"),
    path("psicopedagogica/<int:avaliacao_id>/deletar/", views.psicopedagogica_deletar, name="psicopedagogica_deletar"),
    path("psicopedagogica/<int:avaliacao_id>/observacoes/", views.salvar_observacoes_psicopedagogica, name="salvar_observacoes_psicopedagogica"),
    path("psicopedagogica/<int:avaliacao_id>/visualizar/<int:pagina>/", views.psicopedagogica_visualizar, name="psicopedagogica_visualizar"),
    path("psicopedagogica/publico/<str:token>/<int:pagina>/", views.psicopedagogica_publico, name="psicopedagogica_publico"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__404__/", lambda r: render(r, "erros/404.html", status=404)),
        path("__403__/", lambda r: render(r, "403.html", status=403)),
        path("__500__/", lambda r: render(r, "500.html", status=500)),
    ]
